### ISSUE TITLE
Administration area

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#11]
_From @joaopapereira on September 4, 2015 16:30_

As an administrator
When I visit /admin
I can see the administration area
Where I can change the the configurations of the application

_Copied from original issue: AgileVentures/MetPlus_PETS#42_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
When I go to this page (as admin) I have previously been 1) added as a user to PETS, and 2) assigned 'admin' role for a specific agency).  (*NOTE: we need an 'agency manager' role who could assign a user to 'admin' role for a specific agency*)

Functions available (on or linked to this page):
1) Edit my "standard" user attributes (name, email, password, etc.)
2) Edit attributes of the agency for which I am admin (name, description, phone, website, addresses, etc.)
3) Add a  job developer to agency - this will result in an email going to the JD with a link to go to page to finish JD registration.
4) Add a  case manager to agency - this will result in an email going to the CM with a link to go to page to finish CM registration.
5) Add an Employer - this will result in an email going to the Employee contact with a link to go to page to finish Employer registration.  (*NOTE: we probably need a page for employer to use to indicate interest to become an Employer associated with this agency - this would result in adding a task for the admin to process this request (which process would include a vetting and approval of that Employer)*)

**Comment by joaopapereira** [comment]
I have mixed feeling about the edit standard information, I believe that should be separated.
The adminstration area should be specific for administrative tasks, like option 2-5.
What do you think?

**Comment by patmbolger** [comment]
I agree.  My thought was to just add a link to the standard user-edit page, just as a convenience - but it is not required and might be more clutter than a convenience.

**Comment by patmbolger** [comment]
- [ ] Cucumber Scenarios
    - [ ] Login as admin and end up on main admin page
    - [ ] Click on "Edit" for addresses and end up on edit page
    - [ ] Add an agency address and save
- [ ] DB schema design extensions - as needed to support above items
- [ ] Rspec tests to support scenarios
- [ ] Add code to support at least one scenario

**Comment by joaopapereira** [comment]
What is missing in this task?

**Comment by patmbolger** [comment]
I revised the task list to reflect the actions I took for this issue. 

I will add separate issues for other work to extend the admin feature set.  

So, I think we can close this issue.
