### ISSUE TITLE
Bootstraping devise views

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#110]
As User, I should see proper formated UI with  bootstrap.

**Comment by amba178** [comment]
- Since bootstrap is available to through cdn, we should take advantage of bootstraping our views.

**Comment by joaopapereira** [comment]
This task cannot start until we have a UI defined. Unless this i is just to add the bootstrap css file link

**Comment by amba178** [comment]
@joao:  Make sense, any free wireframing tool you think of.

**Comment by amba178** [comment]
@joao: Make sense. Would be nice if you talk about wireframing briefly in scrum or PP. I understanding the whole concept, but  never used wireframing tool before.

**Comment by joaopapereira** [comment]
This task is very generic, we will open a task per page implementation instead
