### ISSUE TITLE
Home page layout

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#112]
As a developer
I need a wireframe of the home page

**Comment by joaopapereira** [comment]
In this task we expect:
- Generic home page for someone not logged in
- Basic structure with call to action depending on the future role of the User

**Comment by sidhene** [comment]
Ready for review. Work include changes to Navbar, call to action research (Hired.com, Hackbright.com), and wireframe updates. Will discuss in scrum.
https://cacoo.com/diagrams/giWg1CL8f7KbtEXx/edit
https://github.com/sidhene/MetPlus_PETS/tree/development

**Comment by sidhene** [comment]
Is this done? Not sure if I'm waiting to be asked for changes or if I should close and pick a new ticket.

**Comment by joaopapereira** [comment]
If it is approved by the team. I will give it a new label the waiting client answer. After his feedback we can close it or send it back to In progress.
Do you agree with this?

**Comment by sidhene** [comment]
Sure! I was mostly just worried that I hadn't understood the work request because it turned out to be so easy.

**Comment by joaopapereira** [comment]
The client said that the home page design as a starting point was enough. So we can proceed with the implementation
