### ISSUE TITLE
JS Registration page layout

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#114]
As a developer
I need a wireframe of the registration page

**Comment by joaopapereira** [comment]
Expected:
- Generic layout for a Job Seeker

**Comment by joaopapereira** [comment]
Is there still a question for this issue?

**Comment by patmbolger** [comment]
We should probably review as a team on Monday.

Then, we can jump into the implementation (is there an issue for that yet?)

**Comment by joaopapereira** [comment]
Fields:
- First name
- Last name
- Email address
- Phone number
- Password
- Confirmation Password
- Year of Birth
- Resume file(Upload box)

**Comment by vijayakarumudi** [comment]
I finished the wireframe for JS Registration layout.

**Comment by vijayakarumudi** [comment]
Here is the link to the layout https://docs.google.com/document/d/1N494xMJYTXvDt19G6_6cEx1p1AH_kje_YfttXdeYPq4/edit?usp=sharing

**Comment by vijayakarumudi** [comment]
Here is the link to the layout with updates following team review
https://docs.google.com/document/d/1tNQu-_egJOI29rAuKyOEIAp25v_KXnf76UqLkExeiwg/edit?usp=sharing

**Comment by joaopapereira** [comment]
Looks good, I believe we can start implementing it.

**Comment by vijayakarumudi** [comment]
I am working on the implementation.

**Comment by joaopapereira** [comment]
client  approved the current design, eventually the fields will change

**Comment by vijayakarumudi** [comment]
Thanks for the update.
