### ISSUE TITLE
Strong parameters for update

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#117]
Devise implement Strong parameters separately for each form.As result, our app does not allow us to update the user/fields for edit.

**Comment by joaopapereira** [comment]
I prefer that you start developing the #124 or the #113 instead of solving this, because it is related with the registration and the registration was working.

**Comment by amba178** [comment]
@joaopapereira: sorry guys I missed the scrum today, and I was way the whole day. Anyway, I am very sure works, is not about solve it,  I was looking  for alternative way as Patrick mentioned that this might cause thread safety as a result might cause the test fail and I knew the side effect while adding the file. Basically, it forces to share the threads among the test, and in our app most complicated thing so we have done so far is login, then edit user profiles thus forces login thread to be shared with edit. But login by itself we dont need to worry about it. I would say we should use it, shared_db_connection.rb file.

**Comment by amba178** [comment]
This should be working and is in synch with support/env file with Patrick one.  I will start with 124, 113 and should be straight forward implementation.
