### ISSUE TITLE
Upload Resume - JobSeeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#120]
As a Job Seeker,
While visiting the website www.metplus.org
I can register on the site (create an account)
And I can upload my resume

**Comment by joaopapereira** [comment]
See JS:JA/2

**Comment by joaopapereira** [comment]
Prepare PETS to upload Resume
 [] Create Service class
 [ ] Create connectivity method
 [ ] Create method in the service to upload the file
 [ ] Create field in registration form for resume upload

**Comment by patmbolger** [comment]
- [ ] Job Seeker registration form - upload résumé
  - User can enter file name in text field
  - User can 'browse' to select file on local drive
  - Validate entered / selected file type is acceptable
  - upload résumé into Tempfile 
  - User must have option "I don't want to upload a résumé at this time."

- [ ] Resume model
  - validate acceptable file type

- [ ] Job Seeker controller
  - validate resume, render 'new' if fails
  - save resume if job seeker save successfully (render 'new' if fails)

- [ ] Tests (unit, functional, acceptance)

This story does *not* include:
- Updating resume (this will be added to user profile edit)
- Deleting uploaded resume (this will be added to user profile edit)
- Uploading multiple resumes
