### ISSUE TITLE
Employer Registration page layout

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#121]
As a developer
I want to create a wireframe with the registration form for an Employer

**Comment by joaopapereira** [comment]
Expected:

Generic layout for a Employer

**Comment by sidhene** [comment]
https://docs.google.com/drawings/d/1f6ASzGARD4KZzlIh_ozPPnjfWZ7U5yigApVcpYcJk3I/edit

**Comment by sidhene** [comment]
Layout completed. LMK if I should add details about how each element corresponds with backend model/field/tables.

**Comment by sidhene** [comment]
Added confirmation page: https://docs.google.com/drawings/d/1scVVfgD-qk7-QFM3Eg0NsWYBciDB45jtmCeaSR7kfyM/edit

**Comment by joaopapereira** [comment]
Going to share these 2 with Chet

**Comment by sidhene** [comment]
Chet says we're good to go (see comments on two google docs) so I'm moving this to 'done'.
