### ISSUE TITLE
Add new Case Manager

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#13]
_From @joaopapereira on September 4, 2015 16:28_

As a Case Manager
I receive an email from the website with the invitation to join
Then using the provided link I enter the website
And fill the form with the missing information

_Copied from original issue: AgileVentures/MetPlus_PETS#26_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
This has been resolved with PR #142
