### ISSUE TITLE
Job Seeker Registration

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#130]
As a job seeker
I want to register with the agency

As a Job Developer
I want to register a job seeker with my agency

As a Case Manager
I want to register a job seeker with my agency

As an agency admin
I want to register a job seeker with my agency

**Comment by patmbolger** [comment]
I include multiple scenarios which don't neccessarily represent different functions but rather capabilities managed by cancancan.

**Comment by joaopapereira** [comment]
Blocked by #114

**Comment by joaopapereira** [comment]
Expected:
- [ ] Controller
 - [ ] New Endpoint
  - [ ] Create a new JS from the model
  - [ ] Validate the JS
  - [ ] Save JS
- [ ] HAML
 - [ ] New Template
  - [ ] Create new template with the layout from #114

**Comment by vijayakarumudi** [comment]
I  assigned  this task to myself.
