### ISSUE TITLE
Notify the Agency administrator of a new Employer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#133]
As a developer
I need to implement the notification sent to the Agency 
When a new Employer register in the website

**Comment by joaopapereira** [comment]
In this story after the creation of the employer a new notification is placed in the notification system to alert the Agency Personal that a new Employer need to be approved

**Comment by patmbolger** [comment]
This is gated by #186

**Comment by joaopapereira** [comment]
* Add to the registration controller a call to the notification subsystem
* Add a email template
* Add a controller endpoint for the email
