### ISSUE TITLE
Redesign the home page

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#141]
As a developer, I want to redesign the homepage. 
possible contents: 
  * Featured jobs
  *  Success story
  *  Some statement regarding the Goal of MetPlus/maybe at launch time

Inquire client any specific content would like  to see on the homepage.
 MetPlus logo png,  for favicon.

**Comment by amba178** [comment]
Assume we have 100s of jobs to display and do we want the user to scroll to see the next 30 jobs.

**Comment by amba178** [comment]
Assume we have 100s of jobs to display and do we want the user to scroll to see the next 30 jobs.

**Comment by joaopapereira** [comment]
Change verbage on access to registration forms

**Comment by patmbolger** [comment]
Includes removing the 'New User' link from navbar.
