### ISSUE TITLE
Add fields to the register/edit job seeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#142]
As a developer
I need to add the remaining fields

**Comment by joaopapereira** [comment]
In the registration form we are missing the field:
job seeker status

**Comment by vijayakarumudi** [comment]
I am working on jobseeker status field. I  added the status field to form and writing  rspec tests.

**Comment by vijayakarumudi** [comment]
In this story I completed rspec and cucumber tests. I will create the PR after rebase the latest from development.
