### ISSUE TITLE
Update company person

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#146]
As a user, I should be able to view and edit my profile as appropriate to my user type

**Comment by amba178** [comment]
By click this link, it should render edit page view correctly to respective users.
users can be js, jd, admin, agency, etc

**Comment by sidhene** [comment]
Hey guys,

I've been digesting the revelation that #edit and _form are already claimed for AgencyPerson, and tried a couple of approaches to make up for it. I think the best approach at this point - since AgencyPerson personal profile update is currently identical to the out-of-the-box Devise functionality - is to do nothing and let AgencyPerson use the Devise profile update. 

If we're going to have different levels of users, and different profile editing (from an admin doing user management and from users managing their personal preferences) the right place for these personal profile edits is probably the Users directory (currently named 'devise'). We should discuss this.

I have appointments today and tomorrow that will keep me out of scrum, but I'm around mornings and will keep you updated via Slack/Waffle/Github until I'm free again Friday.

**Comment by patmbolger** [comment]
Devise is great at managing user accounts (create, edit, delete) with incredible functionality OOB (email confirmation, user invitation, password resets, etc.).  

Devise also is designed to accommodate more than one "user account" model - for instance, you could have a User model, an Admin model and a Guest model, all managed separately by Devise, and each customizable (views, controller actions) to its specific needs.

We have chosen to use a single Devise user model, which meets our needs and keeps things simple.  However, we have, in actuality, three different types of users and thus de-facto user accounts.  However, using separate user accounts in Devise for each of the three would not work for us given that these three are not entirely separate but share a common User model.

So, trying to customize Devise to differentiate the 3 types of users would not be in line with how Devise was designed, and therefore is probably not the way to go.

Also, each of the 3 types of user will have unique attributes in the future (today, all user attributes are the same across the 3 types, except for attribute 'title', which is part of the CompanyPerson model - but this will no doubt change in the future).

So, I recommend we use separate (from Devise) controllers and views to manage the profile for each such user type.   Specifically, for **phase 1**:

- [ ] We already have edit and update actions in job_seekers_controller.rb.  These work fine. 
- [ ] We add actions edit_profile and update_profile to agency_people_controller.rb.  Later, when we implement cancancan authorization, we will allow that method to be available to a logged-in agency person (with verification that the edited profile actually is owned by that person).
- [ ] We create the view edit_profile for those actions.  
- [ ] We execute the above two steps also for company_people_controller.rb.
	
This is the work that could be done for *waffle #146*.

**Phase 2** would consist of DRY'ing out duplicate code - mostly in views, where each of the 3 views involved in profile management would contain duplicate fields for User attributes.  There may also be helpers that can be shared across views.  (I don't think there is a waffle story for this yet).

**Comment by sidhene** [comment]
Originally 'edit all users' but JobSeeker is being handled by another story and Agency_Person will require  a different approach since #edit and #update have been already claimed by other functions.

**Comment by patmbolger** [comment]
" ... Agency_Person will require a different approach since #edit and #update have been already claimed by other functions."

Note that this is also the case for CompanyPerson.

**Comment by sidhene** [comment]
Okay. Let's have an architectural discussion, because right now we're structuring our code with two different conventions - jobseeker vs agencyperson - and we should figure out something that will be easy for any new coders we add to understand.

**Comment by sidhene** [comment]
BTW just noticed: this (and all the other issues) are listed under _tracker, when they really belong under _PETS
