### ISSUE TITLE
"show" methods for Company and CompanyPerson

### ISSUE THREAD

**Issue by sidhene** [AgileVentures/MetPlus_tracker#158]
As an agent or company contact, I would like to view my Company information

**Comment by patmbolger** [comment]
Amy - did you mean for this to be a story for adding a #show command for company_registration?   I think we need that first.

If so, please be aware that there is a #show command now, except it needs to have these additions:

- [ ] company contact
- [ ] company address

**Comment by sidhene** [comment]
Ok. I created this story as a 'stub' to meet the best practice of 'never work without a story'. Feel free to elaborate, and let's discuss it with the team on Monday.

**Comment by sidhene** [comment]
obsolete, patrick has this on another ticket
