### ISSUE TITLE
DRY out address create, update and show

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#159]
As a developer
I want to have one form that is used for address management

**Comment by patmbolger** [comment]
We collect address information is multiple places, including company registrations, company edit, AgencyPerson create/edit, CompanyPerson create/edit, JobSeeker create/edit, Agency branch create/edit, and others.

We should have one common form (partial) for address data this is used in all of the places where address data is managed.

**Comment by amba178** [comment]
@team: Do we need to add state column to addresses table?

**Comment by patmbolger** [comment]
Yes, I think we need 'state' attribute.  We could do this as part of this story.

**Comment by vijayakarumudi** [comment]
I assigned this task to my self.
