### ISSUE TITLE
Add new Job Developer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#16]
_From @joaopapereira on September 4, 2015 16:27_

As an Administrator
I enter the administration panel
And create a new account giving the Job Developer Role
Then the Job Developer will be notified

_Copied from original issue: AgileVentures/MetPlus_PETS#23_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by vijayakarumudi** [comment]
I assigned this task to myself.

**Comment by joaopapereira** [comment]
This issue is blocked by #11

**Comment by patmbolger** [comment]
Yes, we need added agency admin functionality.  Recommend moving this to backlog for now.

**Comment by patmbolger** [comment]
This was completed in PR #142.
