### ISSUE TITLE
Add 'Cancel' to login form

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#162]
As a user
I want to  be able to cancel out of the login form
And be back on the page from which I clicked "Login"

**Comment by patmbolger** [comment]
Enhance the user login feature:
- [ ] Allow user to cancel login and return to page the user was on when he/she clicked the 'login' button
- [ ] After successful login, the user should return to page the user was on when he/she clicked the 'login' button

**Comment by amba178** [comment]
The second part a bit complex, it forces us maybe to override session control for devise, and utilize session.  @patmbolger : Do you have any rough idea how to go about it.

**Comment by patmbolger** [comment]
Suggest these as possible approaches:

1) Possibly redirect back to prior page - here are some ideas:  http://stackoverflow.com/questions/2139996/how-to-redirect-to-previous-page-in-ruby-on-rails

2) Change login form to be a pop-up (modal) dialog box over the current page.  Look at what I did for the company registration 'deny' action.  (register a company registration request as a site visitor, login as agency admin, click on company name in the admin home page, then click 'Deny' button).
