### ISSUE TITLE
Job CRUD actions

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#173]
As an agency (or company) admin
I want to be able to create, edit, delete and show jobs

**Comment by patmbolger** [comment]
This story includes the creation of *jobs_controller.rb* with these initial actions:

- [ ] new
- [ ] create
- [ ] edit
- [ ] update
- [ ] show
- [ ] destroy

The pages to be created are shown in this mini site map:

https://www.draw.io/#G0ByK45zp6m5k4QXo4MDNHQnlpUU0

**Comment by patmbolger** [comment]
Salem - as part of this I think you should also make the DB changes we discussed (and are included in the latest version of the ERD (a PR for the ERD in pending for those changes).

**Comment by amba178** [comment]
@patmbolger:  Good idea, I will update the history.
