### ISSUE TITLE
Job CRUD(index, show, edit, new, delete) wireframes

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#176]
As a developer, I want put wireframes together before start implementing UI.

**Comment by amba178** [comment]
This is the link to all wireframes: http://zc6evg.axshare.com. Under the discussion, you can leave comment or suggestion.

**Comment by amba178** [comment]
@patmbolger  : You raised a  good point  on the jobs wireframe even though this story is specific to CRUD, I do have some feature on wireframe  which are not related to the task. For example as you pointed out in the jobs/:id or jobs.  These features will be stubbed out or hard coded as place holder.

**Comment by sidhene** [comment]
See also #34

**Comment by sidhene** [comment]
A couple of questions:
- How are JobSeekers supposed to apply for jobs? 
I didn't find any description in the System Behavior documents. There's two obvious possibilities: instructions ("to apply, send resume and cover letter to jobs@employer.com") in the job description itself or using the contact info in the #show view
- Should 'jobs/id' (#show) include the contact info? 
Usually employers keep the hiring manager's email under wraps, which means only AgencyPeople should be able to see this information.

**Comment by amba178** [comment]
Before  going to your question, this task/story purely deals with job CRUD behaviors  
simple stuff, there  are no any associations implemented yet. Probably, you will some placeholder in the UIs which are either stubbed or hard coded. 
For example, in the job list edit and delete links should be hidden from jobseeker or from unauthorized person and so on.
Ok.
 On your first point,  Yes those are two possibilities  a jobseeker can apply for the job.
if the contact info belongs to hiring manager than probably that is right. But let say if a jobseeker assigned to CM, than he should be able to see the contact info.  
Your questions are valid, and we should discuss as a group. 
Mean while, Checkout the Job model and its associations.

**Comment by sidhene** [comment]
Isn't this done? Salem has a pull request for #173, which was for the implementation. So the design was probably finished some time ago.

**Comment by patmbolger** [comment]
I agree Amy.  Your questions here are also good and should not be forgotten about - but they pertain to work that will occur as follow-on to this story, so we can revisit them then.

In the meantime, I will move this to "Archive" status.
