### ISSUE TITLE
Job Developer Search Job for a Job Seeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#18]
As a Job Developer
Given a Job Seeker's skills
The system search for matches of jobs
And I can have the search filter by how close the Job Seeker matches the job requirements
And this includes a range from "exact match" to "no match"
And I can submit a job application for the job seeker regardless of match

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
Asked the client if this requirement is correct

**Comment by joaopapereira** [comment]
_From @patmbolger on October 7, 2015 17:45_

We assume this feature is also available (or exclusively available?) to Job Developers.  Please confirm.

**Comment by joaopapereira** [comment]
JS:JD/1

**Comment by patmbolger** [comment]
see JS:JD/1

**Comment by patmbolger** [comment]
See related (design) story #350.

**Comment by patmbolger** [comment]
This story is being implemented - partially - in #388.  For MVP, we will not have the ability to show a range of matches.
