### ISSUE TITLE
JobSeeker Status Required

### ISSUE THREAD

**Issue by vijayakarumudi** [AgileVentures/MetPlus_tracker#183]
As a developer, I want to ensure that jobseeker selects a value for status on the registration page.

**Comment by sidhene** [comment]
For clarification: we're requiring this at the model level, just like year of birth, correct?

**Comment by patmbolger** [comment]
Yes, we should validate presence of job_seeker_status in the job_seeker model.

**Comment by sidhene** [comment]
Done.
