### ISSUE TITLE
Create service to connect with Resume Cruncher

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#189]
As a developer
I need to create a service that can connect with the Resume Cruncher

**Comment by joaopapereira** [comment]
A suggestion for the implementation of this can be found in this link: http://blog.codeship.com/architecting-rails-apps-as-microservices/
The easiest way to archive this is by using MicroServices architecture and the previous link shows how to implement a Micro Service

**Comment by joaopapereira** [comment]
Latest documentation on the cruncher can be found in: http://joaopapereira.github.io/MetPlus_resumeCruncher/

**Comment by joaopapereira** [comment]
Gist of a sample of connection: https://gist.github.com/joaopapereira/ebb945c7d5a6622bac21

**Comment by joaopapereira** [comment]
Needed implementation:
- Create a new library to connect to the Java cruncher
- Create the function to authenticate the service
- For now UT need to be implemented
- Integration tests should be performed only inside the Rails stack, no real interaction with the Java service

**Comment by patmbolger** [comment]
Initial thoughts on design of service:

CruncherService:
> Implemented as a class rather than library as it will contain domain-specific logic
> establishes communication channel
> persists authorization token (class var?, session?)
> handles communication errors
> provides specific API's for actions (post resume, retrieve resume, find jobs matching resume, etc.)
> If required, hands off tasks to Delayed Job
> Logs events
> Authentication will use name/password maintained in application.yml

**Comment by joaopapereira** [comment]
Eventually we can add this to a model, I believe that the connection layer should be separated.
ResumeCruncher will be the class that have the functions
ResumeCruncherService the connection itself

Not sure if delayed jobs will work for us, because we need to have response from the service in order to continue

The rest looks good.

**Comment by patmbolger** [comment]
This is a more complete work-up of what I am thinking in terms of class structure:

class **CruncherService**
- establish comm channel
- persist with token once channel is established
- handle comm errors
- log events
- backend credentials stored in application.yml

class **ResumeCruncher**
- provides specific API's for actions (post resume, retrieve resume, find jobs matching resume, etc.)
- interacts with CruncherService to effect communications with cruncher

class **JobCruncher**
- provides specific API's for actions (post job, find resumes matching job, find jobs similar to a given job, etc.)
- interacts with CruncherService to effect communications with cruncher


Example of using the service: 
- assume we define a Resume model (which will be needed as we will need to store the name of the resume passed to the cruncher, and we may allow a user to have multiple resumes stored in the future)
- the Resume model has at least these two methods:
  - #upload  (analogous to 'save')
  - self.retrieve (analogous to 'find')

These methods use the ResumeCruncher API to do their work.

In general, the ResumeCruncher and JobCruncher methods may be invoked in models or controllers, as appropriate.
