### ISSUE TITLE
Job Developer search for Job Seekers

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#19]
As a Job Developer
I can search Job Seekers that match the skills of a specific Job

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
Asked the client if this requirement is correct

**Comment by joaopapereira** [comment]
After client feedback this story will be dropped

**Comment by patmbolger** [comment]
see JS:JD/1

**Comment by patmbolger** [comment]
This is the same as #98.

**Comment by joaopapereira** [comment]
Can we close this story then @patmbolger ?
