### ISSUE TITLE
Creating/implementing  job-company association

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#192]
As a developer, I want to create job-company association.

**Comment by joaopapereira** [comment]
Before starting the development we should vote on the story

**Comment by amba178** [comment]
Sure.

**Comment by patmbolger** [comment]
This actually includes job<>company person and job<>company associations

**Comment by amba178** [comment]
Sorry guys, it shouldn't have taken me long to do my PR. I was busy with work.
