### ISSUE TITLE
Job Seeker home page - wireframe

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#203]
As a developer
I want to develop a wireframe for the job seeker home page

**Comment by sidhene** [comment]
https://docs.google.com/drawings/d/1Fi8DyYARYkS-_tOgTMB9a2-VYgJpIhoxB6HPsm1-eFs/edit

**Comment by sidhene** [comment]
Here's what I think they need to see:

Profile information
Agency contact(s) with title (ie "Case Manager")
The status of their job applications
A list of available jobs

Am I missing anything?

**Comment by sidhene** [comment]
Ready for review. It will look much better coded, since GDocs is kind of a blunt instrument (I wasn't able to shrink the table rows, for example), but it does a good job of showing what will go where.

**Comment by patmbolger** [comment]
Comments on wireframe ( can't comment in Gdocs as I have view-only access):

1. "Caseworker" should instead by "Case Manager"
2. Please add "Job Developer" as well (this is the JD who is assigned as "primary" job developer to this job seeker)
3. Of the 3 tables, "Your Applications" should be shown first, followed by "Best Matches", and then "New Opportunities"
4. I am not sure we need the "Apply Now" buttons.  Perhaps a hint to the user like "Click on the job title to view and apply".   (we also don't want to have the user simply apply to the job before viewing the complete job description on the "Show" page - that show page will then contain the "Apply" button).
5. Each of table should support pagination.  You could just add a note (to the developer) on the page, or perhaps show pagination elements on at least one of the tables (see image below).
6. Consider changing the table rendering to a cleaner look (IMO) - without column separators.  For example:

<img width="705" alt="screen shot 2016-03-03 at 6 51 20 am" src="https://cloud.githubusercontent.com/assets/9968213/13493487/5fcd6214-e10c-11e5-9557-15f626a1a59a.png">

**Comment by sidhene** [comment]
1. Done
2. Done
3. That was an auto-formatting by gdocs and not supposed to be there. Fixed
4. Done but still using "matches" as example table view
5. This is how it’s usually done. We need to let the user explore but still provide a single call to action. I agree they should view the job before applying, so let’s make that part of the workflow. Do we have a doc where I can record this decision?
Also, we need to find out from the client what the most important call to action will be
6. OK. I haven’t added it to the wireframe bc GDocs doesn’t really have the capacity
7. OK, but same as #6 - not sure table can be formatted at all in Gdoc
