### ISSUE TITLE
Action Authorizations matrix

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#205]
As a developer 
I need to specific authorizations for specific actions

**Comment by patmbolger** [comment]
As an example, a company admin, *and* an agency admin, can edit a company person profile.

This should be developed as a table( with actions in columns and authorized roles in rows,  for example)

**Comment by vijayakarumudi** [comment]
I am  working on this one.

**Comment by vijayakarumudi** [comment]
Here is the link for the authorization matrix
https://docs.google.com/spreadsheets/d/1RD0pCovjiOiqBQZeIUMLbXGuWEHO4jLEC4Mj0xjlD-k/edit#gid=0

**Comment by joaopapereira** [comment]
One question, what are these actions related to?

**Comment by vijayakarumudi** [comment]
Here the latest link for the authorization matrix
https://docs.google.com/spreadsheets/d/1s5SplUumtTtjKMbZMCODeZehLzB-wND32IowZxiEL5Q/edit?usp=sharing

**Comment by vijayakarumudi** [comment]
Here is the link https://docs.google.com/spreadsheets/d/1s5SplUumtTtjKMbZMCODeZehLzB-wND32IowZxiEL5Q/edit

**Comment by patmbolger** [comment]
Vijaya - for some reason I still cannot edit the sheet via the above link. 

I ended up copying and extending it.

This is the link for that: https://docs.google.com/spreadsheets/d/1XmlNwVebV3ix1wU0GgXk39mOanHviDLZdod_xdnfqpE/edit?usp=sharing

I also added this to the "System Behavior and Design" page on AV: http://www.agileventures.org/projects/metplus/documents/system-behavior

**Comment by vijayakarumudi** [comment]
Patrick: I reviewed PETS User Auth  Matrix. it looks good.
