### ISSUE TITLE
UI improvements March 1

### ISSUE THREAD

**Issue by sidhene** [AgileVentures/MetPlus_tracker#207]
(this story serves as a bucket for small changes that don't merit their own story)
As a user, I would like the following improvements to MetPlus to make it easier to navigate:

Agency Admin/agency people:
listings of job seekers should link to jobseeker#show views

**Comment by sidhene** [comment]
email:
Jobseeker welcome email says "Welcome [email@address]!" instead of "Welcome [name]!"

**Comment by sidhene** [comment]
Front page: 
Need link to create jobseeker just like we have for hiring partners 
-OR-
"New User" page needs to offer choices for type of user

**Comment by joaopapereira** [comment]
Change the view to add links to the text(Agency Person show page)
