### ISSUE TITLE
Registration of an Employer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#21]
_From @joaopapereira on September 4, 2015 16:26_

As a Employer
I register my company into the website
Then I wait for feedback from the Administration 
Then I can go back to the website and do login

_Copied from original issue: AgileVentures/MetPlus_PETS#16_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
see JD:E/2

**Comment by patmbolger** [comment]
When an employer is added to PETS, then employees (of that employer) can register as employer contacts.  We need to define how the employee confirms that they are with the Employer.  Perhaps we assigned a unique ID when the Employer registration is approved, and the employee uses that to confirm their association with the Employer.

**Comment by sidhene** [comment]
1. CreateRecord: Employer
2. Create 'action required' (approve employer) for agency
3. Confirm Employer (make active)
4. Create user: employer contact

**Comment by joaopapereira** [comment]
Expected in this task:
- [ ] Controller
 - [ ] New endpoint
  - [ ] Create Company from the model
  - [ ] Validate the information
  - [ ] Save the provisional Company
  - [ ] Create CompanyPerson from the model
  - [ ] Validate the information
  - [ ] Save the provisional CompanyPerson
- [ ] HAML
 - [ ] New template based on issue #121

Rspec and Cucumber tests to validate the previous actions

**Comment by sidhene** [comment]
The "provisional" function mentioned in Joao's comment above has been moved to #136

**Comment by joaopapereira** [comment]
Yes and no.
In 136 we will implement a function to change status
But the comment is still correct because the Company need to be created as a provisional company

**Comment by sidhene** [comment]
No, it needs to be created period and the provisional function added in 136. #136 will then include the work of updating the Company model, etc.

**Comment by sidhene** [comment]
Hey guys - the display on my laptop is broken and I'm going to have to get it fixed. Given how long I've held this already, do you want me to hand this off or should I just keep on keeping on and not worry about the delay?

**Comment by sidhene** [comment]
I have Company working and Company_Person mostly working, but it's running into issues that I think are related to rules in User/Devise. I'll need to pair with someone to figure it out.

**Comment by sidhene** [comment]
Hey team: 
I've been without Internet service since my last check in. I have a technician coming Monday to fix it hopefully, but I'm blocked until then. I making this update through my phone. Please share this information since I can't reach Slack or anything else

**Comment by sidhene** [comment]
The story has changed quite a bit, mainly because of the complication of registering both a person and a company on the same page. Patrick created CompanyRegistrations to manage this, and is going to write tests for its create, etc. functions. I've reassigned the story to him and he'll pass it back to me when he's done with this so I can make the final tweaks and submit a pull request.

**Comment by patmbolger** [comment]
I added acceptance (cucumber) and functional (spec) tests for company registration.  Assigning back to Amy for final review and PR creation.

(Amy - had to make a couple of minor changes to your form to make it more testable - e.g. differentiating between company email and contact email - so Capybara can see field as distinct).
