### ISSUE TITLE
Job Category management

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#210]
As a user
I need to manage job categories
Which are used for multiple purposes
Including assigning job specialties to agency people
And assigning a job to a category
And defining what skills are needed for jobs within a specific category

**Comment by patmbolger** [comment]
This is phase 1 for JobCategory.

Business requirements and design considerations and decisions are discussed below.

**Use Cases**:

1.  **Agency person add/edit/delete categories**
  - Perhaps we need a new role to authorize this?  (including skills editing) - YES, since we need to have a small group of people focused on maintaining a coherent, non-duplicative set of categories.  Too many people with this ability would be difficult to manage.
2.  **Company person associates a job with a category**
  * If appropriate category not available:
    * Issue request to agency admin? - YES
      * Assign to placeholder category in the meantime
      * Agency request: R/T notification, email and task creation
    * Allow to create new category?  - NO
      * This could be chaotic - see discussion above
      * Categories are common across companies, so need to be uniform and be managed by the agency

**Design Considerations**:

1.  There will be *many* categories
2.  Categories are not nested (so there could be much duplication of some aspects of specific categories)
  * Should they be nested? - NO - for now, *leave as flat structure*
3.  Will need *search capability* to narrow view of categories
  * Reduce duplication
  * Allow focused view of specific set of categories
4. Model attribute 'name' must be unique
  * This forces categories to be unique (description attribute will *not* be forced to  be unique)

**Comment by amba178** [comment]
On the use cases:  2
   * if we are enforcing uniqueness of the attribute 'name',  why not allow the company person to create category one  on the fly,  if it doesn't exist?

**Comment by patmbolger** [comment]
The primary reason is that there is only one set of categories for all jobs on the site (no subcategories, for instance).  This makes is very important for whoever is managing categories to have a consistent approach to those, and this means that there should be a few people (at most) within an agency who manage categories.  That approach has to consider naming conventions, whether and how to use abbreviations, and level of granularity to adopt.  This latter is very important.   For instance, there is a great deal of difference between:

1. "Software Developer"
2. "Software Engineer - Full-stack development"
3. "Senior Software Engineer - Ruby on Rails, React.js, Bootstrap"

The first choice means many fewer categories and more detail in the job description regarding the specific skills required for a particular job.   The third choice means many more categories will be required, and perhaps less detail in the job description.  And, of course, the second choice is somewhere in the middle.

Without central control there could be a complete mix of approaches and that could be OK or it could be a nightmare.

The other reason for not allowing company people to create categories is that job categories are the same set across all companies.   Since each company may have a different approach to defining categories, this could definitely lead to chaos.

**Comment by amba178** [comment]
Well put. Can we say, a job can have many categories?

**Comment by patmbolger** [comment]
No, a job has one category (in fact, it has a 'belongs_to :job_category' association).

(once we build this as-designed lets review and see if we want to make any changes based on what we learn)
