### ISSUE TITLE
Associating job with job_skills

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#213]
As a developer,  I want to create job<>job_category association.

**Comment by patmbolger** [comment]
This is gated by the first phase of #210

**Comment by joaopapereira** [comment]
Add to the job edit view:
 * List job categories
 * List of associated categories
Add to the job add view:
 * List job categories
 * List of associated categories
Add to the job show view:
 * List of categories associated with the job

**Comment by patmbolger** [comment]
I changed the title to reflect our change in design.  Now, a jib will be associated directly with specific job skills, and will not be associated with a job category.

**Comment by patmbolger** [comment]
This was completed with waffle #268.
