### ISSUE TITLE
Create Agency Person role for job properties management

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#216]
As an agency person
I need to be able to manage job properties, such as job categories and skill definitions

**Comment by patmbolger** [comment]
See comments in waffle #210 for more information (https://waffle.io/AgileVentures/MetPlus_tracker/cards/56d6f080c3d7e6830039fdfd)

**Comment by patmbolger** [comment]
We don't need this for MVP.

**Comment by joaopapereira** [comment]
Create a role inside the agency that will only have access to manage these properties

**Comment by patmbolger** [comment]
This is completed.  The agency admin can manage job properties via the admin menu item "Job Properties".
