### ISSUE TITLE
Job Developer home page

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#226]
As a registered Job Developer
When I login to PETS
I should be directed to a personalized 'home page'

**Comment by sidhene** [comment]
See #226
See #227
Both are content for home page, but this can be developed independently, as a placeholder

**Comment by sidhene** [comment]
This is where the Jobseeker will be direct upon login
Includes: 
view (container)
controller
spec for http success

**Comment by sidhene** [comment]
Went to work on the redirect and realize we need conditional roots. This is an architectural decision that has not been implemented yet and should be discussed as a team. I will bring it up in Scrum.
