### ISSUE TITLE
List JS related with JD

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#227]
As a Job Developer
I want to see all my Job Seekers in my home page

**Comment by joaopapereira** [comment]
Connected #226
* Create a partial/or use the partial for #229
* Add the partial to the home page of Job Developer
* Create a controller point for this partial/add to the homepage show endpoint
* Add the function to the model that will retrieve all the Job Seekers connected with one Job Developer

**Comment by sidhene** [comment]
This actually already exists as part of the /admin/agency_people/#show view

**Comment by sidhene** [comment]
covered in #226
