### ISSUE TITLE
Post Job - affiliated with agency

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#23]
_From @joaopapereira on September 4, 2015 16:26_

As an Employer affiliated with the agency,
While visiting the website www.metplus.org
I can add a new job description
And all Job Developers are notified

_Copied from original issue: AgileVentures/MetPlus_PETS#14_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
see JD:E/4
