### ISSUE TITLE
Case Manager home page

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#230]
As a registered Case Manager
I want a home page with relevant information.

**Comment by joaopapereira** [comment]
Create the page controller and view
Create a list of all the items that should be displayed to the Case Manager

Ex:
- List of JS that the CM is associated with
   - Name
   - Last login date
   - Other field
- List Of JS without CM associated
   - Name
   - Registration date

**Comment by sidhene** [comment]
New wrinkle: I believe it's not only possible but likely that the same person could be both a job developer and a case manager.

If this were so, we can't send them to two different pages at once. But we can have an agency_person/home page and display the relevant information with conditional statements.  I'll bring this up today in Scrum.

**Comment by sidhene** [comment]
Additional requirement: redirect to this page after AgencyPerson login (carried from 226)

**Comment by sidhene** [comment]
Is this done? We have the page controller and view. We have the redirect (which is what I was planning to do today). 

The next step is to either break out the jobseeker lists into reusable partials, or generate them in place, the way we have JS lists for the JD role now. The creation of these two lists are stories #231 and #234. 

Moving to 'needs review' for discussion at standup. I'll pick up another CM story.
