### ISSUE TITLE
List of job seekers not assigned to a case manager

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#234]
As a Case Manager
On my home page
I want to see all the Job Seekers who are not yet assigned a case manager

**Comment by joaopapereira** [comment]
Move the method to retrieve all JS without CM(Suggestion: JS Class method)
Change the CM homepage endpoint to call the previous function
Create a view(partial maybe used in JD homepage)

**Comment by patmbolger** [comment]
This has been delivered with #315.
