### ISSUE TITLE
Unit tests for helper methods

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#247]
As a developer
I need to ensure sufficient test coverage

**Comment by patmbolger** [comment]
In support of #226, these methods were added to app/helpers/agency_people_helper.rb:

- [ ] job_seekers_without_job_developer
- [ ] job_seekers_without_case_manager
- [ ] job_seekers_without_agency_person_in_role(role_key)

These need to have tests added in agency_people_helper_spec.rb.

**Comment by joaopapereira** [comment]
Is this task still needed?

**Comment by patmbolger** [comment]
Closing this as not needed due to refactoring.
