### ISSUE TITLE
Upload Resume

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#25]
_From @joaopapereira on September 4, 2015 16:26_

As a Case Manager,
While visiting the website www.metplus.org
I can upload a resume in behalf or a Job Seeker

_Copied from original issue: AgileVentures/MetPlus_PETS#12_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
_From @patmbolger on October 7, 2015 17:27_

Note this action (adding a JS résumé to PETS) by the case manager also includes: 1) creating an account in PETS for the JS, 2) filling out the JS profile, and 3) establishing an association between the JS and the Job Agency where the case manager works.

**Comment by patmbolger** [comment]
See JS:CM/1, JS:CM/2, JS:CM/3

**Comment by joaopapereira** [comment]
Is this already implemented?

**Comment by joaopapereira** [comment]
Please review the story and if it is complete we can close it. If not move it back to backlog
