### ISSUE TITLE
Custom login redirects

### ISSUE THREAD

**Issue by sidhene** [AgileVentures/MetPlus_tracker#250]
Case Managers, Job Developers, and other roles should be redirected to a custom home page after logging in according to their role. This requirement is mentioned in #226 and #230. Because this development would affect the site as a whole, we are abstracting it into a custom story

**Comment by sidhene** [comment]
Alternately instead of custom redirects, we might just want to send everyone to the same Home page and custom-populate it with the correct modules according to role.

**Comment by joaopapereira** [comment]
This story will be closed because it is already solved by AgileVentures/MetPlus_tracker#258
