### ISSUE TITLE
View JS information

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#251]
As a developer
I need to create a view of JS information for CA, CC, JD, CM

**Comment by patmbolger** [comment]
**Company Person**
- [ ] Show view:
    - name
    - email (link_to mailer)
    - address
    - résumé (link to view résumé in-line)  (future?)
    - job developer (link to  AP 'show' view)
    - No edit/delete buttons
    - 'Applications to < company name > jobs'
		
    - [ ] Accessing JS show view:
      - CP home page - list of company jobs
        - [ ] column "number of applications" - number is a link to job applications page (to be created for this story)
      - [ ]  job applications page
        - summary of job at top
        - list of JS who have applied to job
        - JS name is link to JS show view
				
**Job Developer**
- [ ] AgencyPerson home page - 'Your Job Seekers'
    - Name is link to Company person show view
      - JS info - Same as for company person
      - 'Job Applications for < job seeker >
        - [ ] list job and company primary data  (already built)
        - [ ] job title is link to job applications page
				
**Case Manager**
  - same as Job Developer
	
**Agency Admin**
  - same as Job Developer, except:
  - [ ] JS home view
    - 'Edit' button
    - 'Delete' button
