### ISSUE TITLE
Implement Authorization matrix using Pundit

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#253]
As a developer
I need to implement the authorization matrix using Pundit library

**Comment by joaopapereira** [comment]
https://docs.google.com/spreadsheets/d/1XmlNwVebV3ix1wU0GgXk39mOanHviDLZdod_xdnfqpE/edit#gid=0

**Comment by patmbolger** [comment]
This is being implemented by multiple, discrete (by model/controller) stories.
