### ISSUE TITLE
Refactor route for JobSeeker home

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#265]
The name of the route for job seeker home is: job_seekers_home

When it should be home_job_seeker

**Comment by sidhene** [comment]
like:
resources :company_people do
     get 'edit_profile', on: :member, as: :edit_profile
     patch 'update_profile', on: :member, as: :update_profile
     get 'home', on: :member, as: :home
  end

**Comment by sidhene** [comment]
resources :job_seekers do
  get 'home', on: :member
  end
