### ISSUE TITLE
Associate job categories with skills

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#267]
As an agency admin
I need to associate a job category with skills that might be needed or desired for jobs in that category

**Comment by joaopapereira** [comment]
Changes needed:
Controller:
* Job Categories, endpoint update to find the skills that should be associated with the category and update them
Views:
* Update job category show to add the skills associated with
* Add on the edit job category view the possibility to associate/deassociate skills

Tests to check previous behaviour is correct

**Comment by patmbolger** [comment]
We have removed job<>category association so this story no longer needed.
