### ISSUE TITLE
Associate a job with specific skills

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#268]
As a person creating a job opportunity in PETS
I need to associate specific skills that may be required or desired for that job

**Comment by patmbolger** [comment]
A job is first associated with a job category.

That job category will have skills already associated with the category.

So, the skills available to be associated with the new job will be the skills associated with the job category that the job is assigned to.

**Comment by joaopapereira** [comment]
Blocked by AgileVentures/MetPlus_tracker#267

**Comment by joaopapereira** [comment]
- Change the view to allow the user to add skills when editing a job
- Change the controller to accept the skills


2 options:
- In body of the form, add checkboxes to select the skills 
- In body of the form, add a drag and drop for the skills
