### ISSUE TITLE
Assign CM to JS

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#269]
As a developer 
I need to create the way to assign a Case Manager to a Job Seeker

**Comment by joaopapereira** [comment]
Changes needed:
View:
* create a modal with a select with all the Case Manager in the agency
* Add the modal to the Job Seeker Home page
* Add the select to the edit job seeker profile

Controller:
* Job Seeker controller create a endpoint that will assign a Case manager to the Job Seeker
* Ensure that the update button and the controller is only visible to the CM and AA

**Comment by patmbolger** [comment]
This functionality is delivered via 1) agency admin can assign a case manager to a job seeker, and 2) a case manager can assign himself/herself to a job seeker.
