### ISSUE TITLE
Assign JD to JS

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#270]
As a developer 
I need to create the way to assign a Job Developer to a Job Seeker

**Comment by joaopapereira** [comment]
Changes needed:
View:
* create a modal with a select with all the Job Developers in the agency
* Add the modal to the Job Seeker Home page
* Add the select to the edit job seeker profile

Controller:
* Job Seeker controller create a endpoint that will assign a Job Developer to the Job Seeker
* Ensure that the update button and the controller is only visible to the JD and AA

**Comment by patmbolger** [comment]
I don't think that the select should be added to the JS edit profile page - that page is for the specific user to change name, password, etc.

It should probably be on the AgencyPerson home page, and only available of current_user is a job developer.

(similar comment applies to #269)

**Comment by patmbolger** [comment]
This functionality is delivered via 1) agency admin can assign a job developer to a job seeker, and 2) a job developer can assign himself/herself to a job seeker.
