### ISSUE TITLE
NameError in Users::ConfirmationsController#show

### ISSUE THREAD

**Issue by sidhene** [AgileVentures/MetPlus_tracker#274]
To reproduce:
sign up as a job seeker
click confirmation email link

What should happen:
"you have been confirmed!"

What happens instead:
Error page

NameError in Users::ConfirmationsController#show 

uninitialized class variable @@delay in Event

app/models/event.rb:24:in `create'
app/controllers/users/confirmations_controller.rb:18:in `block in show'
app/controllers/users/confirmations_controller.rb:15:in `show'

HOWEVER - the new user gets created and I can log in

**Comment by sidhene** [comment]
I performed the test discussed in today's scrum and bug is gone. Apparently this only happens if server is left running when codebase is upgraded.

**Comment by joaopapereira** [comment]
Going to close this issue
