### ISSUE TITLE
Upload Resume - Job Seeker

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#28]
PETS-2: As a Job Seeker,
While visiting the website www.metplus.org
I can register on the site (create an account)
And I can upload my resume

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
- [ ] Prepare PETS to upload Resume
 - [x] Create Service class
 - [x] Create connectivity method
 - [ ] Create method in the service to upload the file
 - [ ] Create field in registration form for resume upload
- [ ] Prepare ResumeCruncher to upload Resume
 - [x] Create database object to store the Resume and the meta data
 - [x] Create class to parse pdf and word file into the object
 - [x] Create controller for resume
 - [ ] Create endpoint to upload Resume

**Comment by joaopapereira** [comment]
_From @patmbolger on October 6, 2015 20:59_

Is this feature wanted by the client (we do not list this action in the "Roles and interactions" document)?

**Comment by joaopapereira** [comment]
In this story we implement the feature to upload the resume to the Resume Cruncher. We will ask the client if a Job Seeker can create an account. If not we can remove the sub task "Create field in registration form for resume upload"

**Comment by patmbolger** [comment]
See JS:JA/2
