### ISSUE TITLE
Integrate jobs creation in cruncher

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#288]
As a developer
I need to implement a function to create a job in the cruncher

**Comment by joaopapereira** [comment]
Add a new model for JobCruncher similar to ResumeCruncher

Add a function to create/edit a job in the CruncherService

Job Model, override save and call the JobCruncher to upload the job after successful save

Testing for the new components

**Comment by vijayakarumudi** [comment]
I am assigning this to myself.
