### ISSUE TITLE
Show timestamps to users that correspond to their time zone

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#292]
As a developer
I need to show times to users that are converted to their time zone

**Comment by patmbolger** [comment]
We need a javascript method that will convert UTC time (as derived from DB timestamps) to the time in the user's time zone.

For example, this code in view/job_seekers/_form.html.haml' needs to be converted to show user-local time instead of a hard-wired server time zone:
```
= "(Your resume on file is \"#{@current_resume.file_name}\",   |
  and was uploaded on #{@current_resume.updated_at.            |
  in_time_zone('Eastern Time (US & Canada)').to_s(:long)})"    |
```

**Comment by sandhyakoti** [comment]
In the client side, once the DOM is rendered(Jquery ready function()), use moment.js to convert the UTC time to local time.
