### ISSUE TITLE
Rejected Job Application

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#298]
As a Job Seeker
I want to apply to jobs on the Job Agency site with which I am associated
And when I apply to a job that I am not qualified for
I get rejected and information is sent to my Job Developer at the Job Agency

**Comment by patmbolger** [comment]
This is part of #374

**Comment by patmbolger** [comment]
Removing MVP label as this story is accommodated by another MVP story.
