### ISSUE TITLE
Track status on agency

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#30]
As a Job Developer
When a Job Seeker applies directly to a job
And I am working on that job with the Employer
I want to alerted that the job application has occurred

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
see JS:E/1

**Comment by patmbolger** [comment]
see JS:E/1

**Comment by joaopapereira** [comment]
Is this done?

**Comment by patmbolger** [comment]
complete
