### ISSUE TITLE
Notification on job application

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#300]
As a developer
I need to implement the notifications when the job seeker applies to a job

**Comment by joaopapereira** [comment]
- Create Event to be sent to the Assigned Job Developer and Company Person that created the job
- Create a Task type called job_application that targets a specific Company

**Comment by patmbolger** [comment]
From document 'Roles and interactions' (http://www.agileventures.org/projects/metplus/documents/roles-and-interactions):

*JS:E/1*
  - JS submits résumé to E (employer) directly.  This can be done online in PETS or via providing the JS unique identifier in PETS (email) to the employer (e.g., at a job fair).
When this occurs the CM and the JD will be notified.

Aggregating all thoughts above the story becomes:

----------------------------------------------------------------------------------
When a job seeker applies directly to a job in PETS:
----------------------------------------------------------------------------------

- [ ] Notify the job seeker's case manager (notify == popup and email)
- [ ] Notify the job seeker's job developer
- [ ] If the job was created by a company contact, notify the company contact
- [ ] If the job was created by an Agency Person (e.g. job developer):
    - Notify the job developer (unless the JD was already notified in step 2 above)
    - Notify the company admin(s)
- [ ] Create a Task type called job_application (to be reviewed), visible to audience:
    - All company personnel (contacts and admins)

----------------------------------------------------------------------------------
