### ISSUE TITLE
Add Skills model

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#305]
As a developer
I need to add the skills model to the database

**Comment by joaopapereira** [comment]
- Add a new model called Skills with the field Name(We will be using this as the feature repository or something similar)
- Add the CRUD operations

**Comment by patmbolger** [comment]
I think we'd do better converting JobCategory to SkillsCategory.

**Comment by joaopapereira** [comment]
This is a ResumeCruncher story
