### ISSUE TITLE
Phone Validation too restrictive

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#308]
As a developer
I want my validations to conform to real-world use

**Comment by patmbolger** [comment]
Current validation is:
```
def validate_each(object, attribute, value)
    return if value == nil
    reg = /^(\+\d{1,3} )?\(?\d{3}\)?( |-)?\d{3}( |-)?\d{4}$/
    unless value.match reg
      object.errors[attribute] << (options[:message] || 'incorrect format')
    end
end
```
This is too restrictive as it does not accommodate office extensions, such as:

222-333-4545 x23,

432-289-3788 ext. 29

etc.

Also, the error message should be enhanced to provide more information to the user as what constitutes a correct format.

**Comment by patmbolger** [comment]
See background here: https://github.com/AgileVentures/MetPlus_PETS/wiki/Validating-Phone-(and-fax)-Numbers

It is preferred that waffle #366 be finished first, as this story build on that logic.

**Comment by dsmegha** [comment]
#366? Or you mean #367?

**Comment by patmbolger** [comment]
Yes, I meant #367.
