### ISSUE TITLE
Refactor the 'find agency person' process

### ISSUE THREAD

**Issue by sidhene** [AgileVentures/MetPlus_tracker#313]
from https://github.com/AgileVentures/MetPlus_PETS/pull/261 
"there are multiple functions that do the same thing, or are very similar.

"The function to assign the agency person currently looks like to much code

"possibly also factor "@your_jobseekers_jd " to JobSeeker.with_job_developer @agencyperson"

**Comment by sidhene** [comment]
much of the awkwardness is the result of trying to make pagination work. now that we have a different pagination these constraints no longer apply

**Comment by patmbolger** [comment]
Closing and archiving this as it appears it is no longer needed.
