### ISSUE TITLE
Track status

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#32]
_From @joaopapereira on September 4, 2015 16:25_

As a Job Seeker
I can visit www.metplus.org
And check status in Job application

_Copied from original issue: AgileVentures/MetPlus_PETS#5_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by joaopapereira** [comment]
I believe this is complete correct @patmbolger ?

**Comment by patmbolger** [comment]
yes will close
