### ISSUE TITLE
Add query API's to Cruncher Service

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#322]
As a developer
I want to determine if a specific résumé already exists in the Cruncher
And I want to determine if a specific job already exists in the Cruncher

**Comment by patmbolger** [comment]
- [ ] Add API to allow querying the existence of a résumé by 'userId'
- [ ] Add API to allow querying the existence of a job by 'jobId'

**Comment by joaopapereira** [comment]
@patmbolger  What is the Use Case behind this story?

**Comment by patmbolger** [comment]
Can't remember. 

We can close this.
