### ISSUE TITLE
Add 'match score' to Cruncher API return values

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#323]
As a developer
I want to show a relative match score to a user
For both matching a résumé to jobs
And vice versa

**Comment by patmbolger** [comment]
Current capability of cruncher matching is this:

1. Given a resume, return all matching jobs
2. Given a job, return all matching resumes

These API's should be enhanced with a "match score", on a scale of 1 to 5 (1 = no/low match, 5 = excellent match).  In other words:

1. Given a resume, return all matching jobs and match scores for each
2. Given a job, return all matching resumes and match scores for each

**Comment by joaopapereira** [comment]
Getting shipped with #336
