### ISSUE TITLE
Fetch jobs that match a résumé

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#332]
As a developer 
I need to implement the endpoint to match jobs with a specific resume

**Comment by joaopapereira** [comment]
Add match function on ResumeCruncher to match job based on a specific Resume ID
Add function to CruncherService to execute the function to match jobs against a resume:  http://joaopapereira.github.io/MetPlus_resumeCruncher/#match-jobs-with-resume


Test the functions at ResumeCruncher level and CruncerService level, RSPEC

**Comment by patmbolger** [comment]
The Cruncher backend has the capability to return jobs that match a specific résumé.

This story is to implement a method, in class CruncherService, that invokes that cruncher API with the ID of a specific résumé and receives back a list of job titles matching that résumé.

The method has to handle errors cleanly, and return a list of job titles to the caller.

**Comment by patmbolger** [comment]
Cruncher API documentation: http://joaopapereira.github.io/MetPlus_resumeCruncher/#match-resumes-with-job-description

**Comment by joaopapereira** [comment]
Request information
POST /api/v1/curriculum/match HTTP/1.1
X-Auth-Token: 2be76720-3fd8-4651-bd0e-0d21df11c1fd
Accept: application/json
Host: localhost
Content-Type: application/x-www-form-urlencoded

title=Stone+mason&description=Stone+mason+that+is+able+to+build+some+nice+walls

**Comment by joaopapereira** [comment]
[ ]  Create a new function in CruncherService.match_jobs(resume_id) to call the previous endpoint with a get.  The answer will be  a map with the job ID
[ ] Create a new function in JobCruncher to call the service
