### ISSUE TITLE
JD create job opportunity layout

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#34]
As a Job Developer
I create a job opportunity from Employer description

**Comment by patmbolger** [comment]
see JD:E/3

**Comment by sidhene** [comment]
Design: https://docs.google.com/drawings/d/1hMau8kHEULq8kgV_oN1jg-zLpNr9B5eUobdOkuO0GFo/edit

**Comment by patmbolger** [comment]
This is premature for sprint 4 - recommend moving to backlog.
