### ISSUE TITLE
Agency Admin cannot edit Agency Info

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#351]
As a developer 
I need to fix bugs

**Comment by patmbolger** [comment]
Log in as agency admin
Go to Admin > Agency and Partner Companies
Click button 'Edit Agency'
See message 'You are not authorized to edit MetPlus agency.'

**Comment by vijayakarumudi** [comment]
This is working on my development environment.

**Comment by patmbolger** [comment]
Bug not reproducible.  Maybe due to rails server becoming out of sync with DBV object?
