### ISSUE TITLE
Add JobApplication life-cycle states

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#370]
As a developer
I need to add states to the JobApplication model

**Comment by patmbolger** [comment]
The states are defined in the second table here: http://www.agileventures.org/projects/metplus/documents/system-behavior

- [ ] Add to the model, e.g.
```
STATES = {ACTIVE: 'active',
          ACCEPTED: 'accepted',
          NOT_ACCEPTED: 'not_accepted'}
```
- [ ] Create a migration file to add field to DB

- [ ] Add test(s) as needed to job_application_spec.rb

**Comment by dsmegha** [comment]
The JobApplication db already has a field called status.

class JobApplication < ActiveRecord::Base
  belongs_to :job_seeker
  belongs_to :job
  enum status: [:pending, :rejected, :hired]

  def status_name
    status.to_s.camelcase
  end
end

Should I edit this status to reflect the System Behavior and Design, ie active, filled and revoked?

**Comment by patmbolger** [comment]
Yes, that field was added as a placeholder before we had a life-cycle design for JobApplication (JA).

So, yes, please use that field (enums actually work very well for modeling a simple state machine).

Note that the as-designed JA states are: active, accepted, not_accepted

**Comment by dsmegha** [comment]
Thanks Patrick. I will use the same field. And yes states are active, accepted and not_accepted. My bad.
