### ISSUE TITLE
Implement Job state change to 'filled'

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#373]
As a user with appropriate authorization
When I accept a job application
I want the associated job status to be set to 'filled'

**Comment by patmbolger** [comment]
See job states as defined in this page:  http://www.agileventures.org/projects/metplus/documents/system-behavior

Note that this state change is initiated by a related JobApplication being set to 'accepted' state (see separate story for that).

This story includes:

- [ ] Set job status to 'filled'

- [ ] Change job 'view' logic so that a job application *cannot* be submitted to a filled job

**Comment by jeanwei** [comment]
The functionality is delivered together with #372
