### ISSUE TITLE
Task model needs an admin field

### ISSUE THREAD

**Issue by dsmegha** [AgileVentures/MetPlus_tracker#378]
When a task is created, it is has a status 'new' and is automatically assigned to the an agency person. This means that one or more of 'owner_user_id: nil, owner_agency_id: 1, owner_agency_role: "AA" ' is set. However when the agency person assigns this task to a job developer/case manager the owner_user_id, owner_agency_id, owner_agency_role fields are changed to reflect the new task owner and all the details of the agency admin who made this change is lost. We need a way to preserve this data.

**Comment by dsmegha** [comment]
Example entry in the Task model before and after the task is assigned to a person.

Task id: 1, task_type: "need_case_manager", owner_user_id: nil, owner_agency_id: 1, owner_agency_role: "AA", owner_company_id: nil, owner_company_role: nil, deferred_date: nil, user_id: 426, job_id: nil, company_id: nil, status: "New", created_at: "2016-07-18 06:00:53", updated_at: "2016-07-18 06:00:53"

Task id: 1, task_type: "need_case_manager", owner_user_id: 430, owner_agency_id: nil, owner_agency_role: nil, owner_company_id: nil, owner_company_role: nil, deferred_date: nil, user_id: 426, job_id: nil, company_id: nil, status: "Assigned", created_at: "2016-07-18 06:00:53", updated_at: "2016-07-18 06:19:30"

The owner_agency_id: 1 and owner_agency_role:"AA" are lost once the job is assigned to an person with the id 430. There is no way currently to track who made this change.

**Comment by joaopapereira** [comment]
Solution implementation for this issue:
Create functions:
Task.find_by_company(company_person)
Task.find_by_agency(agency_person)

These 2 functions will return the ActiveRecord object with the result( we will use this later if we want to restrict by any specific status). This should be a simple query where we compare the task owner company/agency with the user passed in to the function.

You can see example in the scope agency_person_tasks/company_person_tasks.

Also we need to make sure that these functions are only callable by admins of Company and Agency. To do that we need to implement policies using pundit.
Please take a look at app/policies/task_policy.tb to see the policies that we implemented so far.

**Comment by patmbolger** [comment]
This story has been addressed in other stories, so closing it.
