### ISSUE TITLE
Download résumé for a job seeker

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#385]
As a developer
I need to provide a capability to download a résumé for a specific job seeker
For various purposes
For instance, so that the résumé can be used for a job application
Or, the résumé can be viewed online

**Comment by patmbolger** [comment]
Add class method *download_file* to CruncherService class.

This has to communicate back to the caller where to find the downloaded file.

It also has to cleanly handle errors.

**Comment by patmbolger** [comment]
Cruncher API documentation: http://joaopapereira.github.io/MetPlus_resumeCruncher/#match-resumes-with-job-description

**Comment by joaopapereira** [comment]
- [ ] Create a function to dowload the resume CruncherService.download_file(resume_id) will return a File Handler
- [ ] Create a function ResumeCruncher.download_resume(resume_id, resume_name) 


API Information
GET /api/v1/curriculum/asdasdasd

**Comment by joaopapereira** [comment]
Check the mechanism to download from the webservice and pass it to the user(Real user that clicks in the download link). Maybe use Tempfile class to store the file temporarily.
