### ISSUE TITLE
DRY out require rails_helper statement from spec files by configuring rspec

### ISSUE THREAD

**Issue by arun1595** [AgileVentures/MetPlus_tracker#395]
In every spec file that we write, we include a `require` statement which requires `rails_helper`. To dry it out, we can configure rspec to automatically require `rails_helper` in every *_spec.rb

To fix:
- Replace `--require spec_helper` with `--require rails_helper` in .rspec file
- Remove `require 'rails_helper' from *_spec.rb`

Note: `spec_helper` is required in `rails_helper` so we can safely replace it.

**Comment by patmbolger** [comment]
The *require 'rails_helper'*  statement is included automatically when an rspec file is created by a 'rails generate' command.  Should we change that as well to *not* include that in a new *_spec.rb* file?

**Comment by arun1595** [comment]
Actually I didn't know that the `require` will be generated by `rails generators`. As I don't have any solution to avoid this, I will better close this.
