### ISSUE TITLE
User redirect to JS index page upon JS registration failure

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#415]
As a developer
I want to ensure that user navigation occurs within design intent
And also that private information is protected

**Comment by patmbolger** [comment]
During the UX review of September 1, 2016, Sam failed to created a job seeker registration and, when he clicked the back arrow, was directed to a job seekers index page - which exposed personal info (email, phone) of all job seekers in the DB.

Video: https://www.youtube.com/watch?v=bxhmpuNkFrc&feature=youtu.be

Watch from 11:00 through 12:00 to see the bug.

In this situation, the user should be directed back to the welcome (landing) page.

**Comment by patmbolger** [comment]
Note: this happened on Heroku, pets-dev app.  That may be running as 'production'.  Bug cannot be duplicated in development.

**Comment by pcaston** [comment]
As discussed it doesn't appear that this error can now be re-produced so I'll move it to the done column
