### ISSUE TITLE
Sending job application fails

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#417]
As a job seeker
When I apply to a job
My résumé is not being sent to the company

**Comment by patmbolger** [comment]
When applying to a job using the UI, the email to the company (job_email address) is failing to be sent.

This might be due to the fact that:

1. We send email on a delay, and,
2. When we set up the delayed job for the email, we immediately delete the Tempfile that is to be attached to the email as the user's résumé. (so when the delayed job starts the file is not available)

(note that currently all email delay is turned off for testing, so this problem would not be visible in test).

The failure can be seen from the console output of the delayed job process:
```
[Worker(host:Patricks-MBP.home pid:83575)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=3) RUNNING
[Worker(host:Patricks-MBP.home pid:83575)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=3) FAILED (4 prior attempts) with Errno::ENOENT: No such file or directory @ rb_sysopen - ./tmp/file_id_2_20160910-83580-1dmxj1w
[Worker(host:Patricks-MBP.home pid:83575)] 1 jobs processed at 8.4325 j/s, 1 failed
```

This story:

- [ ] Fix bug

- [ ] Develop a test to confirm this capability (perhaps one acceptance test with delayed job *not* turned off)

**Comment by patmbolger** [comment]
By the way, to send emails via delayed job, start this process in a console:
```
rake jobs:work
```
That periodically scans the DB for jobs and processes them.

**Comment by joaopapereira** [comment]
The retrieval of the file should be done inside the delayed job, instead before creating it.
