### ISSUE TITLE
JD applying for JS - fails with JS w/o résumé

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#418]
As a job developer
I want to apply to a job for a job seeker
But only if that job seeker has a résumé on file

**Comment by patmbolger** [comment]
The select list for job seekers assigned to the job developer (for submitting an application for a job seeker) includes job seekers who have not uploaded a résumé.

For instance, here is a job seeker for whom an application is about to be submitted:

<img width="623" alt="screen shot 2016-09-10 at 7 38 56 am" src="https://cloud.githubusercontent.com/assets/9968213/18410213/ed0a3c70-7729-11e6-9723-8cfbc030e128.png">

And results in this:

<img width="495" alt="screen shot 2016-09-10 at 7 41 21 am" src="https://cloud.githubusercontent.com/assets/9968213/18410216/0407ee86-772a-11e6-9d68-a0c77745346b.png">

Also, please present the list of job seekers in sorted order.  This is how it appears now:

<img width="626" alt="screen shot 2016-09-10 at 7 38 28 am" src="https://cloud.githubusercontent.com/assets/9968213/18410221/22e53804-772a-11e6-81e1-cb09e8b34b41.png">

**Comment by joaopapereira** [comment]
Show all users in the list, but the ones that do not have a resume should be greyed out.
We should also add a note under the box saying: "The Job Seekers not selectable do not have a resume on file. Please contact them in order to allow you to apply for the job"
