### ISSUE TITLE
CM update JS information

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#422]
As a Case Manager
I want to be able to access one of my Job Seekers
And update the information of their profile

**Comment by joaopapereira** [comment]
We can use the Edit Job Seeker screen but we should also inform the Case Manager that they are editing something that is not theirs

**Comment by patmbolger** [comment]
Note: don't worry about authorization for this story - that will be added via a Pundit implementation story.
