### ISSUE TITLE
Add auth to job seekers controller

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#440]
As a developer
I need to enforce authorization for user action

**Comment by patmbolger** [comment]
* See authorizations by role here: https://docs.google.com/spreadsheets/d/1XmlNwVebV3ix1wU0GgXk39mOanHviDLZdod_xdnfqpE/edit#gid=0

* Review Pundit: https://github.com/elabs/pundit

* Review existing implementation of Pundit (e.g. application_policy, etc.)

This story includes:

- [ ] Add job_seeker_policy.rb

- [ ] In job_seekers_controller.rb, authorize actions consistent with auth matrix

- [ ] Add rspec tests for policies

- [ ] Add rspec tests for job_seekers_controller.rb authorizations

*Note* - there is no need for acceptance tests as the controller tests are sufficient for auth functional testing.

**Comment by jeanwei** [comment]
AA is allowed to edit JS field too. Shall we let AA have the same edit field as CM too?

**Comment by patmbolger** [comment]
"Shall we let AA have the same edit field as CM too?" - Yes, lets do that.
