### ISSUE TITLE
Reduce number of seeded data records

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#444]
As a developer
I don't want to wait forever for DB seeding to finish

**Comment by sigu** [comment]
Any special conditions to be considered here before reducing number of seeded data? @anyangocynthia would love to work on this

**Comment by patmbolger** [comment]
@sigu - At first thought:
1) Companies: reduce from 200 to, say, 50.  We can keep the other attribute counts as is (for instance, maintain the count of companies with status "pending registration" at 20).
2) Job categories: probably need only 20 (instead of 200)
3) Skills: can lower to 20 (from 30)
4) Company people: 100 (from 200)
5) Jobs:
  - 25 jobs for "known company" (from 50)
  - 100 jobs for other companies (from 200)
6) Agency branches: 10 (from 50)

That's a good start.  There may be some dependencies amongst objects that break with these number changes (not sure).  Also, would like to get metrics on how much the runtime is reduced (that is, test the time required for ```db:seed``` before and after these changes).
