### ISSUE TITLE
Move list_people action from CompanyPeopleController to CompanyController

### ISSUE THREAD

**Issue by arun1595** [AgileVentures/MetPlus_tracker#450]
From the discussion in https://github.com/AgileVentures/MetPlus_tracker/issues/434, we need to move the `list_people` action to `CompaniesController` and add policies for the same.

**Comment by patmbolger** [comment]
For this story, I think we should just refactor the action to the new controller, but _not_ implement pundit policies for that controller (in this story) since there is already a story for that.
