### ISSUE TITLE
Duplicate notification for Job App accepted & rejected events

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#456]
As a user
I do not want to receive duplicate notifications

**Comment by patmbolger** [comment]
When a job seeker's job application is accepted by the employer, a notification is sent to the job seeker's job developer, and the job seeker's case manager.

Currently, the case manager and the job developer are the same person, that person  is receiving the exact same notification twice.

For this story, ensure that only one notification is sent to the agency person, if that AP has both roles for the job seeker.

**Comment by sigu** [comment]
`Currently, the case manager and the job developer are the same person` 
Should we treat this as the case, that all case managers are job developers

**Comment by patmbolger** [comment]
"Should we treat this as the case, that all case managers are job developers" - NO.

An agency person can have up to 3 roles - Agency Admin, Job Developer (JD) and Case Manager (CM).    A person may have both JD and CM roles,  but that is not always the case.
