### ISSUE TITLE
Job application lifecycle add processing state

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#459]
As a Company Person
When I receive a job application and start the process
I want to press a button to move the application to "Processing" 
To ensure that the system is informed I am considering the Job Seeker

**Comment by joaopapereira** [comment]
The current process have 2 states, 
Active
Rejected/Hired

We need to introduce a new one in the midle

**Comment by hin101** [comment]
The current behaviour is, the company person is presented with two options, either accept or reject the job seeker, so do we need a third button, to say processing, but we keep the job open?

**Comment by joaopapereira** [comment]
Updated the story to add requirement for a button to change the state to Processing
