### ISSUE TITLE
JD show all job seekers matching a job

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#47]
As a Job Developer
When I search for Job Seeker that match a job
I can see matching Job Seekers
And I can apply to the job on behalf of any of the matching job seekers.

**Comment by joaopapereira** [comment]
JD:E/6

**Comment by patmbolger** [comment]
see JD:E/6

**Comment by patmbolger** [comment]
This is similar to #390.

Add a control to the job *show* view that allows for "Find matching job seekers" - this would return all job seekers that match the job, regardless of whether or not any particular job seeker is assigned to the job developer.  The resulting view would allow the job developer to initiate a job application for each job seeker.

**Comment by sigu** [comment]
Is this still a valid story? if so then updated information would be helpful in picking it up

**Comment by patmbolger** [comment]
Actually, this story has been implemented via a couple of other stories.

Closing this story.
