### ISSUE TITLE
Fix job seeker's address attribute

### ISSUE THREAD

**Issue by jeanwei** [AgileVentures/MetPlus_tracker#477]
As a developer
I want to fix bug in job seeker's address attribute

**Comment by jeanwei** [comment]
1. Establish polymorphic association between JobSeeker and Address model
2. Edit JobSeeker controller to ensure address field visibility

**Comment by sigu** [comment]
How can I reproduce this bug in rspec or cucumber, kindly give guidance

**Comment by jeanwei** [comment]
Currently job seeker's address attribute is not well tested. So test will need to be added. 

Part 1:
Currently the relationship of JobSeeker and Address is screwed
![image](https://cloud.githubusercontent.com/assets/16623014/20300715/56d21028-ab5b-11e6-837e-b12f7a4c3c82.png)
This is what we are looking for (using company as the example)
![image](https://cloud.githubusercontent.com/assets/16623014/20300740/6d6af0c0-ab5b-11e6-98d8-edba54c8a2fe.png)

Part 2:
![image](https://cloud.githubusercontent.com/assets/16623014/20300037/337ccf80-ab58-11e6-8a24-1468f2b3ebb1.png)
Address field is missing in the form. 

Test related to model to be done in '.spec' file. while view related do it in '.feature' file.

**Comment by sigu** [comment]
Thanks, now looks more doeable :smile:
