### ISSUE TITLE
Jasmine tests for utc-to-local-timezone

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#479]
As a developer
I want to ensure good test coverage of my codebase

**Comment by patmbolger** [comment]
Add jasmine tests for `utc_to_local.js`

**Comment by lollypop27** [comment]
Installation of Jasmine for Rails:
https://www.sitepoint.com/integrate-jasmine-into-rails-for-solid-javascript-testing/
