### ISSUE TITLE
Refactor download resume to job_seekers controller

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#487]
As a developer
I need to refactor in order to improve the codebase and architecture

**Comment by patmbolger** [comment]
That action is currently in `job_applications_controller` and it to be move to `job_seekers_controller`.

**Comment by patmbolger** [comment]
This includes these tasks:
- [ ] Move action to `job_seekers_controller`
- [ ] Remove route for action (to prior controller) and add route for action (to new controller)
- [ ] Remove policy from `job_application_policy.rb` and add policy to `job_seeker_policy.rb`
- [ ] Change references to path helpers, etc., in views
- [ ] Move/adjust (rspec) controller tests from old controller spec file to new.
- [ ] Move/adjust (rspec) policy tests from old policy spec file to new.
- [ ] Exercise UI to confirm feature still works
- [ ] All rspec tests to pass
- [ ] All cucumber tests to pass

**Comment by pcaston** [comment]
Running tests after merging with development branch

**Comment by pcaston** [comment]
Committed and pushed changes.
