### ISSUE TITLE
Train Cruncher on initial job categories

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#494]

**Comment by patmbolger** [comment]
- [x] Obtain job descriptions from client for initial set of job categories (up to but not more than three)
- [x] Obtain example  résumés from client and other sources for the job categories
- [x] Train cruncher on how to recognize (categorize) each job category (training data), and verify against test data  (including minimal-to-zero false positives and false negatives)
- [x] Train cruncher on how to recognize (categorize) résumés (training data) that match each job category, and verify against test data  (including minimal-to-zero false positives and false negatives)
- [x] Using the API, upload job categories from the front-end and verify correct cruncher processing
- [x] Using the API, upload résumés from the front-end and verify correct correct cruncher processing

**Comment by joaopapereira** [comment]
Done this for a hanfull of categories
