### ISSUE TITLE
BUG: email previews raise exception

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#497]
Certain preview emails for job seeker and agency people notifications fail.  

These failures are due to using emails - that are defined in db/seeds.rb - which have subsequently changed (hence the User.find_by_email method returns nil.

These previews need to the be changed so as to not rely on seeded data.

These are the notifications for agency people which fail:
- [x] job_seeker_applied
- [x] job_application_accepted
- [x] job_application_rejected

This is the notification for job seeker which fails:
- [x] job_applied_by_job_developer

**Comment by patmbolger** [comment]
This is a bug in the mailer preview for this event (previews are accessed at `http://localhost:3000/rails/mailers` when the server has been started.  It looks like this:

<img width="252" alt="screen shot 2016-12-01 at 6 10 52 am" src="https://cloud.githubusercontent.com/assets/9968213/20791845/f58df050-b78c-11e6-848d-af489eff66d1.png">

When the `job_applied_by_job_developer` link is clicked this is seen:

<img width="683" alt="screen shot 2016-12-01 at 6 11 55 am" src="https://cloud.githubusercontent.com/assets/9968213/20791881/198f9544-b78d-11e6-9f10-113b86134fa7.png">

This problem is probably limited to the email preview code, and does not seem to effect the production code that actually sends the email - but this should be confirmed by checking that the rspec tests adequately test that functionality.

**Comment by sigu** [comment]
What we are ultimately interested in is the `agency person` and `application` to be passed in as parameters to the email method call. We can use the first job seeker to create an object from which we can get the relevant `agency person` and `application`

 @patmbolger this is the approach I am giving this, hope its okay
![screenshot from 2017-01-23 20-57-42](https://cloud.githubusercontent.com/assets/584211/22216582/b3e33946-e1b0-11e6-908a-b1ff29732912.png)
