### ISSUE TITLE
JD - JS conflict resolution

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#50]
As a job Developer
I have a primary relationship with a Job Seeker
And when another Job Developer submits that Job Seeker for a job
I am alerted that this has happened

**Comment by patmbolger** [comment]
see JS:JD/3

**Comment by patmbolger** [comment]
gated by #40

**Comment by patmbolger** [comment]
Also related to #35.

**Comment by joaopapereira** [comment]
On event.rb When we notify the Job Seeker we need to check if the Job Developer that applied is the primary Job Developer. If not we should send a email and push a notification.
Add a mailer action to app/mailers/agency_mailer.rb to send this email
