### ISSUE TITLE
Company person profile update - change email

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#506]
When the company person updates their profile with a changed email we need to explain the process to complete this operation.

**Comment by patmbolger** [comment]
When the email is changed a confirmation email will go to the new email address.  When the user changes their email, then, we need to detect that and put up a message that the user needs to confirm the new email address - by clinking on the link in the confirmation email - before the change takes effect.

**Comment by pcaston** [comment]
Unable to run tests because of email validator bug.
