### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by lollypop27** [AgileVentures/MetPlus_tracker#518]
As a visitor,
I would like to see an about page
Where I can find out more about Michigan Employment & Training Plus and the ability to register

See About Us layout: 
https://github.com/AgileVentures/MetPlus_PETS/wiki/UX-Design-Layouts---11-December-2016

**Comment by lollypop27** [comment]
Content for About Page:

Michigan Employment & Training Plus, (MET|PLUS) focus is to help dedicated job seekers with free career information, job insight, skill building and resources needed to effectively help them join the workforce, in order to provide a more fruitful life for themselves and their families. 

MET|PLUS wants to contribute our knowledge and talents to help the rebuilding of Michigan's neglected and damaged communities with various projects and job opportunities. Our organization does not want to reach one goal at a time, but to help achieve multiple goals for Job Employers and Job Seekers together in a faster way.

Mission Statement
TBA

Vision Statment
TBA

**Comment by patmbolger** [comment]
Lara - I added info to the wiki page for "about us" page content (derived from info received from client)
