### ISSUE TITLE
Upgrade ruby

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#528]
Upgrade to the latest stable version of ruby that is compatible with our current version of Rails.

This is Ruby 2.3.3.

**Comment by patmbolger** [comment]
We should stay current with Ruby in order to take advantage of new features.

For instance, we could use the new (2.3) safe navigation operator instead of the slower ```try``` method. (http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

**Comment by sigu** [comment]
Are there major compatibility tests that we should do to make this upgrade or its as simple as changing the ruby version

**Comment by patmbolger** [comment]
@sigu - I don't know.  It's probably as simple as: create a feature branch, upgrade Ruby, run ```bundle install``` and then confirm all tests still work.  But, I don't know at this point.

**Comment by sigu** [comment]
@patmbolger let me look around for any other methods if there is
