### ISSUE TITLE
Add tests for sessions controller

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#536]
app/controllers/users/sessions_controller.rb

**Comment by patmbolger** [comment]
Tests to be added for app/controllers/users/sessions_controller.rb

Tests should cover:
- [ ] user not signed in
- [ ] user signed in
  - [ ] user has checked "remember me"
  - [ ] user has not checked "remember me"
  - [ ] cookies are added (with and without expiration date)
- [ ] cookies are deleted in #destroy action

**Comment by sigu** [comment]
@patmbolger I have done this through feature tests to avoid the complexity of devise and routing in the controllers  :smiley:

**Comment by sigu** [comment]
On second thought, let me take it on with the controllers

**Comment by patmbolger** [comment]
@sigu - OK, sounds good.   And please go ahead and fix the bug - int this story - that you had identified in 561: 
https://waffle.io/AgileVentures/MetPlus_tracker/cards/58a0a0506cae560f00eb0342

**Comment by sigu** [comment]
Sure patrick, I have assigned it to myself and @StlMaris123 . I dont want to mix it up with this issue, it is out of this scope :smiley: So this has to be merged before we start on the other one
