### ISSUE TITLE
Finalize footer content

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#543]
We have a number of different approaches to this and have also veered away from some critical design elements from Lara.

**Comment by patmbolger** [comment]
See related stories:

1. https://github.com/AgileVentures/MetPlus_tracker/issues/534#issuecomment-277622711 - this is the story that implemented Lara's design, with some changes that we need to reconsider.

2. https://github.com/AgileVentures/MetPlus_PETS/pull/501 - some changes to the footer have been made as part of this story.

At this time (Feb 7, 2017) I want to wait for delivery of the 2nd story listed above, and then review and finalize the footer content with Lara et.al.

**Comment by lollypop27** [comment]
@patmbolger sounds good

**Comment by patmbolger** [comment]
Proposed design (to be reviewed with Lara before implementation):

### Left-hand side of footer:

<img width="229" alt="screen shot 2017-02-22 at 10 44 09 am" src="https://cloud.githubusercontent.com/assets/9968213/23219008/dfbc9380-f8eb-11e6-97a8-8d7242647c1d.png">

### Right-hand side contents (differs based on person type):

1) Company Person:
  a. "Home" - link to "Home" ala main menu (note: not the landing page, but the company person home page)
  b. "About"
  c. "Contact"
  d. "Post Job"

2) Agency Person:
  a. "Home" - link to "Home" ala main menu (note: not the landing page, but the agency person home page)
  b. "About"
  c. "Contact"
  d. "Post Job" (if user == job developer)

3) Job Seeker:
  a. "Home" - link to "Home" ala main menu (note: not the landing page, but the job seeker home page)
  b. "About"
  c. "Contact"

4) Visitor (not logged in):
  a. "About"
  b. "Contact"
