### ISSUE TITLE
Add Job Status as searchable field in Jobs index view

### ISSUE THREAD

**Issue by pcaston** [AgileVentures/MetPlus_tracker#544]
As a Met Plus user I want to see the status of jobs
And I want to search jobs by status
So that I can easily access jobs with a desired status.

**Comment by pcaston** [comment]
As discussed with @patmbolger.  Under story 514 the job status is displayed after the job description.   This should be promoted to a fully fledged column so that it is added to the search form and it has a column heading that can be clicked to sort by that status.

**Comment by patmbolger** [comment]
Make sure to update the search help text.
