### ISSUE TITLE
Jobs Search with company pre-selected

### ISSUE THREAD

**Issue by pcaston** [AgileVentures/MetPlus_tracker#545]
As a Company Person
When I click on a Link 'List Company Jobs'
I should see all jobs for my company.

**Comment by pcaston** [comment]
As discussed with @patmbolger.  This could be added as a link to the layouts/_footer.html.haml.  It should be only visible for a company person and invoke the jobs search display with the company name pre-selected as a search parameter.

**Comment by patmbolger** [comment]
See related story #543

**Comment by patmbolger** [comment]
We need to confirm with the client (post-go live) that we need to do this (or not).
