### ISSUE TITLE
Job Seeker - Model creation

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#55]
As a Developer
I want to create the model that supports the Job Seeker

**Comment by joaopapereira** [comment]
Using the ERD to look for the fields.

- [ ]  Create People model
- [ ]  Create PetsAccounts model
- [ ] Create JobSeeker model
- [ ] Create JobSeekerStatus model

**Comment by amba178** [comment]
@joao
For year of birth, you saying four digits/string will be enough, example 1983. Regarding the formating, we could use, DateHelper, the Rails provides for us for free inside  the views:
maybe like select_year,  date_select and  do not have to validate the formating. We can just validates the presence of year of birth. What do you think. if not,  i will just  do it in the JS model

**Comment by joaopapereira** [comment]
@amba178 
Not sure if i follow you. But I believe that for the Year of birth we just need the year not the full date.
Another thing that we need to make sure is that the year is not bigger then the current year, nor smaller then 100 years then the current year mayb

**Comment by amba178** [comment]
Great, much clear now. thanks

**Comment by amba178** [comment]
I looked up http://api.rubyonrails.org/
helper method " select_year"  which does this for us: 

# Generates a select field for years that defaults to the current year that
# has ascending year values.
select_year(Date.today, start_year: 1992, end_year: 2007)

**Comment by amba178** [comment]
I looked up http://api.rubyonrails.org/
select_year helper method 

Generates a select field for years that defaults to current year that
 has ascending year values.
select_year(Date.today, start_year: 1980, end_year: 2015)
