### ISSUE TITLE
Add test for email_validator

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#560]
app/validators/email_validator.rb

**Comment by patmbolger** [comment]
<img width="601" alt="screen shot 2017-02-12 at 10 12 57 am" src="https://cloud.githubusercontent.com/assets/9968213/22863318/d9905e7a-f10b-11e6-9144-30c7496070ae.png">

**Comment by Thomascountz** [comment]
@joesasson is working on this, but can not assign himself ATM
