### ISSUE TITLE
Admin Agency & Partner Page Navigation

### ISSUE THREAD

**Issue by lollypop27** [AgileVentures/MetPlus_tracker#562]

**Comment by lollypop27** [comment]
As an Admin
I want to see a clear navigation on Agency & Partner Admin Page
So I can switch between Agency Information, Agency Branches, Agency Personnel and Companies

See layout:
https://github.com/AgileVentures/MetPlus_PETS/wiki/Agency-Admin-Page

Remove Hide Branches
Remove Hide Companies

**Comment by pcaston** [comment]
Pull request approved
