### ISSUE TITLE
Update profile edit instructions

### ISSUE THREAD

**Issue by sigu** [AgileVentures/MetPlus_tracker#571]
If the jobseeker has already applied for a particular job, they will see a section below the job details telling them to edit their profile if they want employers to see their updated resume. However the instructions tells the user to follow edit process which has changed so far.
The instructions need to give the current directions for editing user profile.

**Comment by sigu** [comment]
![screenshot from 2017-02-19 14-19-21](https://cloud.githubusercontent.com/assets/584211/23101873/1c58f5de-f6af-11e6-91a8-0d0cea18afca.png)

**Comment by sigu** [comment]
**Suggestion:** Could we have it as a clickable link that the user simply clicks to take them to their edit page?

**Comment by patmbolger** [comment]
Yes, we need to update the instructions.  A link would be good as well.
