### ISSUE TITLE
Remove unneeded attribute from JobApplication

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#572]
This attribute is defined in the model:
```
attr_accessor :job_developer
```
However, this does not seem to be used in the production code and appears to be there only for use in some Event model tests.

This attribute should be removed and the tests restructure.

**Comment by patmbolger** [comment]
This is gated by this story: https://waffle.io/AgileVentures/MetPlus_tracker/cards/5826267d1bb74191017066c1

**Comment by pcaston** [comment]
After investigation it seems the attribute is required so that event notifications continue to work for an alternative job developer even though this functionality has not yet been implemented.
