### ISSUE TITLE
Color on Job Application

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#588]
As an Employer
When I Accept a JS Application 
Then the colors of the applications should have color

**Comment by patmbolger** [comment]
Can you elaborate on what is intended here?

**Comment by joaopapereira** [comment]
As a employer after accepting a JS, you still get a list of people that applied to that specific job. What I talked with Chet was that he believes that there should be some color associated with the JS that we display,
Like Green background or the "button" 
The rest of the JS even more greyed out or something similar.


The colors here are just my suggestions, not something that I talked with Chet about

**Comment by joaopapereira** [comment]
Given I acccess the Job  page
When I select a Job Seeker 
And Accept the Job Application
Then I am redirected to the Job Application page
And the selected Job Seeker is on top of the Job Application list
And the border around the Job Seeker should become green


Given I am in Job Application page
When a Job Seeker was accepted
Then I should see Job Seekers not selected greyed out

Given I am in a Job Application page
When  Job Seeker was rejected
Then I should see the application on top of the list with a red border

Given I am in a Job Application page
When a Job Seeker was accepted
And there are Rejected Job Seekers 
Then the Rejected should be displayed right after the Accepted

**Comment by patmbolger** [comment]
This scenarios above are generally fine the I am confused by the third one:
```
Given I am in a Job Application page
When Job Seeker was rejected
Then I should see the application on top of the list with a red border
```
This sounds like a scenario for a job seeker (the one whose application was rejected).  But the other scenarios are written from the POV of the employer.

**Comment by joaopapereira** [comment]
@patmbolger Good question, these stories for now are all in COmpany person and Agency person prespective

```
Given I am in a Job Application page
When any Job Seeker was rejected
Then I should see the rejected application(s) on top of the list with a red border
```

Does this look better?

**Comment by joaopapereira** [comment]
Something similar to this:

![image](https://cloud.githubusercontent.com/assets/1826130/24367848/22c06d72-12ec-11e7-94cd-700b283755c7.png)

Eventually we are missing a column to display the reason.

**Comment by hin101** [comment]
I take it this will be on the job application page and do we want to sort applicants by latest state change?

**Comment by patmbolger** [comment]
@hin101 - this is the job view as seen by a company person (`job_path`).  It looks like the screenshot above except that we have added an "Action" column to that view.

I think sorting the applications by application date (most recent at the top) makes sense.

In any case, we'll run whatever you come up with by the client and get his feedback.
