### ISSUE TITLE
While accepting a job application error message is displayed

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#589]
As a comany person
When I accept a JS application I get the following message:
"Invalid action on inactive job application."

**Comment by patmbolger** [comment]
I cannot duplicate either locally or on Heroku.

Is there any more context available for this bug?

**Comment by joaopapereira** [comment]
It happened to me yesterday in pets-dev.

**Comment by joaopapereira** [comment]
I didnt do much jusy logged in as company person. And accepted one js and the js changed to accepted but yhe page displayed an error

**Comment by joaopapereira** [comment]
@patmbolger lets close this Story, because I do not remember what happened and it didnt happen again, agree?

**Comment by patmbolger** [comment]
Agreed.
