### ISSUE TITLE
Devise Integration

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#60]
As a developer
I should configure Devise to use PetsAccount model

**Comment by joaopapereira** [comment]
Check the problem of having Username and Password in 2 different tables.
Username will be the email inside People table
Password will be inside PetsAccount table

**Comment by amba178** [comment]
@joao:
For validation, we don't need to use the devise validation, right.
Basically, we don't want to override our validation, i guess?

**Comment by joaopapereira** [comment]
@amba178:
1 - We can use our validation
2 - Email - password

**Comment by amba178** [comment]
@joao: 
Thanks.

**Comment by patmbolger** [comment]
Initial implement:

Database Authenticatable
Confirmable
Recoverable
Registrable
Rememberable
Trackable

**Comment by amba178** [comment]
added 
- validatable 
I am doing Devise configuration at Model level, as this task requires.

**Comment by sidhene** [comment]
I think this is done?
