### ISSUE TITLE
Create JS from inside the application

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#605]
**Business Requirements:**

As a Job Developer
I want to be able to create a Job Seeker

As a Case Manager
I want to be able to create a Job Seeker

----

**Stories:**

**Given** That I am in logged in as a Job Developer
**When** I am in the Home Page
**Then** Click in the Add Job Seeker Button
**And** I should see the Job Seeker Creation form

**Given** I filled the Job Seeker Creation Form
**When** I press the Create Button
**Then** The user is created
**And** a Activation Email is sent to the Job Seeker email

**Comment by hin101** [comment]
When the Job Seeker is created, should they be assigned to the Job Developer/Case Manager who created them?

**Comment by joaopapereira** [comment]
Good question for now lets assume no, if we need that we will add it in the future as it will be sa simple change

**Comment by hin101** [comment]
For this story, should the JD/CM be allowed to create a password on behalf of the JS?

**Comment by patmbolger** [comment]
Hinesh asked: "do we want to allow the job developer or case manager, to set a password on the job seekers behalf?"

I think we have to.  Otherwise the account cannot be used and thus is of no good to the agency person.

**Comment by patmbolger** [comment]
For this story, we have to disable the whole Devise confirmation process and create the account (including password) with one form and one controller action.

**Comment by patmbolger** [comment]
A question for the client: assuming the job developer uses the job seeker's email for the account, should a notification email go to the job seeker (that an account has been created on their behalf, with a link to go login, etc..)?

**Comment by joaopapereira** [comment]
Hello, so when I talked with the client he said that the process should be the same as if you were the one registrated as JS.
JS should receive an email in their email address

**Comment by patmbolger** [comment]
@joaopapereira - that email will normally contain a link that the user has to click to 1) confirm the email is valid, and 2) be routed to a PETS form to enter their specific password and thus complete the registration process.  Please confirm whether this story should adhere to that process or if a different one is required.
