### ISSUE TITLE
Company contact should be able to view other company person

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#606]

**Comment by patmbolger** [comment]
When a company contact (company person who is _not_ a company admin) the home screen shows this when the middle button is selected:

<img width="824" alt="screen shot 2017-04-12 at 8 23 31 am" src="https://cloud.githubusercontent.com/assets/9968213/24957322/56bd32b2-1f59-11e7-8279-bbc6d157230d.png">

When one of the company people links is clicked (person name) this is prevented by Pundit:

<img width="913" alt="screen shot 2017-04-12 at 8 24 39 am" src="https://cloud.githubusercontent.com/assets/9968213/24957356/80929ff0-1f59-11e7-97e4-f01967b97a1a.png">

The company contact should be able to go to a view of the company person - which would look like this but **without** the edit and delete buttons:

<img width="763" alt="screen shot 2017-04-12 at 8 25 58 am" src="https://cloud.githubusercontent.com/assets/9968213/24957418/b3be527a-1f59-11e7-9d3c-34bfd42ad2c4.png">

**Comment by joaopapereira** [comment]
Is there any particular reason for this story to be in the backlog if is pointed? Or can it be moved to Ready column?

**Comment by patmbolger** [comment]
Moved to ready column.
