### ISSUE TITLE
Adjust company admin "tasks" menu

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#617]
The tasks menu (with 4 options) wraps the menu too quickly when the browser width is reduced.

See screenshots.

**Comment by patmbolger** [comment]
Here is the company admin (CA) tasks menu when the browser is set to a reasonable width:

<img width="866" alt="screen shot 2017-07-16 at 7 41 15 am" src="https://user-images.githubusercontent.com/9968213/28247269-3a2e126e-69fb-11e7-869a-007c80af065f.png">


---
Here is the CA menu when the browser width is reduced by a small amount:

<img width="722" alt="screen shot 2017-07-16 at 7 41 38 am" src="https://user-images.githubusercontent.com/9968213/28247271-3d922b3e-69fb-11e7-94ea-44e19b10af95.png">


---
In contrast, here is the agency admin (AA) at the same initial width:
<img width="743" alt="screen shot 2017-07-16 at 7 39 44 am" src="https://user-images.githubusercontent.com/9968213/28247277-487d3f8e-69fb-11e7-8516-992f1eeff718.png">


---
And here is the AA menu when the browser width is reduced by the same amount:
<img width="632" alt="screen shot 2017-07-16 at 7 40 05 am" src="https://user-images.githubusercontent.com/9968213/28247280-4bcde184-69fb-11e7-977d-b35ba427e620.png">

I recommend that we:

1) Drop the word "Company" from the tasks menu labels, and,
2) Have the menu options justified-center within their specific divs (have to confirm that this will look OK).  (also, if it looks good, we should go ahead do the same for the AA tasks menu)

**Comment by arku** [comment]
@patmbolger This is the current view of the Company person home page

![image](https://user-images.githubusercontent.com/7039523/28252530-51c54e12-6ab2-11e7-83a2-32c50d1e3b18.png)


This is how it looks after centering the links within the `li`s

![image](https://user-images.githubusercontent.com/7039523/28252527-452a0ea4-6ab2-11e7-9a1c-55672dad2d66.png)

I prefer the former. What do you think?

**Comment by patmbolger** [comment]
Looks good but I actually like the symmetry of the second approach.  Could you please change to that.
