### ISSUE TITLE
Prevent unnecessary page reload - agency person home page

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#620]
We need to perform the same action on the AP home page as for the company person home page as described here:

https://waffle.io/AgileVentures/MetPlus_tracker/cards/596b62fca56a52001be6d49b

The only link (I think) that this applies to is: "Add Job Seeker"

**Comment by arku** [comment]
I fixed this as a part of [https://github.com/AgileVentures/MetPlus_PETS/pull/597](https://github.com/AgileVentures/MetPlus_PETS/pull/597/files#diff-67fca4805d9f0d0c33b49e35625f80a0L54)

**Comment by patmbolger** [comment]
OK, moving this to archive.
