### ISSUE TITLE
Job type

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#623]
As a company person
Given I am creating a Job
I should be able to specify characteristics that define the type of job
Including full-time / part-time, internship (paid / non-paid), contract (and duration of contract), salary / salary-commission / commission-only

**Comment by joaopapereira** [comment]
Mockup: https://www.figma.com/file/0M8E7avMDk5Iu24LgmFgOq7C/MetPlus

**Comment by patmbolger** [comment]
This story requires:

- [x] Add `JobType` model
- [x] In migration file, populate the 7 types in the `job_types` table
- [x] Add associations between `Job` and `JobType` models
- [x] Add test(s) to Job model unit spec tests
- [x] Add JobType model unit tests
- [x] Add type(s) select to Job form (use `select2`)
- [ ] Adjust Job show view to show all types
- [ ] Add acceptance (cucumber) tests

**Comment by hin101** [comment]
Confirmed by @joaopapereira it should be the shift types are the ones in the story:
 full-time / part-time, internship (paid / non-paid), contract (and duration of contract), salary / salary-commission / commission-only

Should we split this story into two? One for these types and one for shift?

**Comment by joaopapereira** [comment]
Lets wait and talk with the client about this story. if this should be placed all in the same Select box or if this should be split, unless @patmbolger as more information about this

**Comment by joaopapereira** [comment]
@patmbolger @hin101 I just updated the comment from Pat to mirror my conversation with Chet today.
This is basically a new field in the form, also updated the figma design with the new field location

**Comment by hin101** [comment]
@joaopapereira @patmbolger "contract (and duration of contract)" do we have a fixed list for duration of contract or should we just simply state contract as job type?

**Comment by patmbolger** [comment]
@hin101 - I would add:

1) A checkbox for "Contract Job", and
2) A pulldown list, with label "Contract Term (months)", with options running from 1 to 24.

It would be nice if the pulldown list would appear when the contract checkbox is checked, and disappear when unchecked - however, we could add that in a subsequent story later as well.

**Comment by hin101** [comment]
@joaopapereira @patmbolger in which case, would it be easier to display all the job types as checkboxes instead?
