### ISSUE TITLE
Seeding DB creates duplicate job applications for job seeker

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#625]
We are creating duplicate job applications (same JS, same job) for job seeker `js1`.

This is probably due to:

At line 242 we create job applications for `js1` for some jobs associated with `known_company`:
```
Job.where(company: known_company).each do |job|
    JobApplication.create(job: job, job_seeker: js1) unless job.id.even?
    Task.new_review_job_application_task job, known_company
end
```
and then at line 254 we create applications for `js1` for the 50 jobs:
```
Job.limit(50).each do |job|
    JobApplication.create(job: job, job_seeker: js1)
end
```
The latter is probably creating duplicate applications for `known_company`.

NOTE: we should use `create!` (instead of `create`) in order to confirm no model validation errors (which would have identified this bug earlier).

**Comment by hin101** [comment]
Is the best solution here simply to just take the first one and discard the second one? or we amend the second one to `JobApplication.create(job: job, job_seeker: js1) unless job.id.odd?` ?

**Comment by patmbolger** [comment]
I would just limit the second job application create section to companies that are _not_ known company:
```
Job.where.not(company: known_company).limit(50).each do |job|
    JobApplication.create!(job: job, job_seeker: js1)
end
```
Also, use `create!`.
