### ISSUE TITLE
Years of experience

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#628]
As a company person
I want to add the minimum years of experience on the current position
So that the Job posting is more complete

Given I am creating a Job
And I correctly fill the form
When years of experience is empty
And I press create
Then the job is created successfully

Given I am creating a Job
And I correctly fill the form
When I enter none numeric values in the years of experience field
Then the 'Invalid number of years of experience' error message shouold be displayed

**Comment by joaopapereira** [comment]
Mockup: https://www.figma.com/file/0M8E7avMDk5Iu24LgmFgOq7C/MetPlus

**Comment by patmbolger** [comment]
I suggest that the "Years of Experience" field be a select list of numbers, ranging from 0 up to 20.

**Comment by patmbolger** [comment]
This story requires:

**Comment by patmbolger** [comment]
This story requires:

- [x] Add `years_of_experience` attribute to model (optional, validate as integer)
- [x] Add test(s) to model unit spec tests
- [x] Add this attribute to Job form
- [x] Add this attribute to Job show view
- [x] Add acceptance (cucumber) tests
  - [x] Leaving the field blank allows the job to be created anyway
  - [x] Selecting a value also allows the job to be created

**Comment by joaopapereira** [comment]
@patmbolger @hin101 Are we still waiting on client feedback for this story?

**Comment by hin101** [comment]
@joaopapereira I have submitted a PR for this story.
