### ISSUE TITLE
Github documentation improvements

### ISSUE THREAD

**Issue by lawsonkeith** [AgileVentures/MetPlus_tracker#63]
Improve github project documentation in Readme.md to better describe project setup to other team members.  

For example: https://github.com/lawsonkeith/Teleop/blob/master/README.md

**Comment by sidhene** [comment]
I'm good at this and going through the process now, so I'll start with this.

**Comment by diraulo** [comment]
I didn't realized there was a ticket for this. I created a wiki earlier on https://github.com/AgileVentures/MetPlus_PETS/wiki

I guess it can be reviewed and edited if needed. Then add a reference to that in README.md

**Comment by sidhene** [comment]
It does need to be edited. I'm re-doing my setup and patching together the how from a combination of the wiki and Railsbridge's "how to git". There are a few missing steps - nothing big, but enough so that the directions won't work if followed exactly.

I was going to just edit the README to point at the wiki. However, I think it's best to have this ticket also represent having a newbie field-test the wiki and update it.

**Comment by sidhene** [comment]
have redone setup and pull request along with review of wiki instructions for same. I have a few edits I'd like to run by someone, which can be previewed here: http://bit.ly/1NYKeAA

**Comment by sidhene** [comment]
status = "done/waiting for QA"

**Comment by lawsonkeith** [comment]
Hi

That looks good I'll run through the it tonight and check it all works.

Keith

**Comment by diraulo** [comment]
@sidhene Added some comments to your document. Other than that rest is OK ;)

**Comment by patmbolger** [comment]
Amy, I added a comment to your doc as well.  Please review (also, Raoul and João)

**Comment by lawsonkeith** [comment]
That's a really good project intro, I ran through it and it and didn't have any problems.  Should be really good for any new members.

**Comment by joaopapereira** [comment]
@sidhene I also added some comments on the document

**Comment by sidhene** [comment]
Thanks!

**Comment by sidhene** [comment]
I'm still not sure the git commands at the pull request are right (details in the 'Dif' doc comments) but since I've less practice with pull requests, I'm going to leave the directions as-is for now.  

All other wiki changes up to date and live.
