### ISSUE TITLE
Import a list of "generic" job skills into DB

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#630]
The system as currently delivered has no job skills in the DB (that is, not "global" job skills).

In order to have skills available for creating jobs, the agency admin currently has to create job skills one-by-one.

This story consists of 1) finding a list of generic job skills (hopefully, with a `name` and `description` for each, so as to map to the fields in the `Skill` model, and 2) a rake task to import that data into the `skills` table.

**Comment by joaopapereira** [comment]
@patmbolger do you think Chet can provide this list for us?

**Comment by hin101** [comment]
@joaopapereira @patmbolger By skill, do we mean generic job titles or soft kills such as communication?

**Comment by patmbolger** [comment]
@joaopapereira - Chet provided me with this link when I asked if he had any information about this: https://www.indeed.com/hire/how-to-write-a-job-description?matchtype=bb&network=search&device=c&keyword=%2Bjob%20%2Bdescription&query=job%20skills%20and%20descriptions&utm_source=bing&utm_medium=cpc&utm_term=job+description&utm_campaign=job+description+pages+general+0+%28bmm%29&utm_medium=cpc&utm_source=google_search&utm_campaign=31809309&utm_term=kwd-31085561680?utm_source=bing&utm_content=job%20description

This is not exactly what we need, but may have helpful examples for entering skills one-by-one (which, of course, we will not do).

@hin101 - here, skill means a capability that is helpful or required for a job.  The skill is can be fairly general ("Excellent oral and written communications", "Office management and administration") or very specific ("Able to type 100 words per minute", "Expert level SQL knowledge").  When a skill is defined, it should _not_ specify whether that skill is required or merely nice-to-have, since the skill by itself is not associated with any specific job.

Then, when a job poster creates a job, he can pick skills from the list of skills and also define whether a skill is required, or nice-to-have.
