### ISSUE TITLE
Integrate task management with associated work activity

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#631]
The client has requested that the system reflect work undertaken due to a task to be reflected in an automatically-updated task status.

For instance, if a job developer is assigned a task that involves assigning himself as JD to a job seeker, when the assignment is performed, the associated task should be updated to the appropriate status (e.g. complete).

**Comment by joaopapereira** [comment]
This story will need to be split into multiple stories, at least one initial one to create the process to link tasks with actions. After that we will reavaluate on the amount of stories needed

**Comment by joaopapereira** [comment]
Closing this story as it was already split
