### ISSUE TITLE
Add color to boxes for application state

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#647]
As an employer reviewing job applications
I want to be able to quickly see the status of each application
So it would be helpful if the status boxes were color-coded

**Comment by patmbolger** [comment]
When a job application has been accepted or reject, we indicate that with a box, under the "Action" column, with text that indicates the final state of the application.

Here is an example of a job with an accepted application.  All other applications are then marked as "not accepted":

<img width="742" alt="screen shot 2017-09-18 at 8 22 18 am" src="https://user-images.githubusercontent.com/9968213/30541978-8e73ae9c-9c4b-11e7-8b26-a312f6219caf.png">

The client would like the status boxes (with test "accepted" and "not_accepted" to have a background color consistent with the scheme: red == not accepted, green == accepted.

Here is another example for a job for which one application has been set to not_accepted:

<img width="736" alt="screen shot 2017-09-18 at 8 26 03 am" src="https://user-images.githubusercontent.com/9968213/30542084-f0900e04-9c4b-11e7-95f6-e00b8215b847.png">

**Comment by tansaku** [comment]
@patmbolger @arun1595 - we're just reviewing the board - this issue was in "needs review" - was there a pull request for this that was already merged?

@joaopapereira do you know anything about this issue?

**Comment by patmbolger** [comment]
@tansaku - to be honest I cannot remember.

**Comment by joaopapereira** [comment]
@tansaku I believe there was no PR for it at least looking at the history of.

**Comment by ashu-22** [comment]
Please ungroup me from all these threads, I do not need any kind of threads from your side, due to I am not being a part of any kind of project that is already being there, So, I won't be able to get all these threads from your side.

**Comment by tansaku** [comment]
@ashu-22 I don't think we can - I think you need to set your github notifications for this project to ignore

**Comment by tansaku** [comment]
@joaopapereira @patmbolger thanks - we'll put this back into the backlog for the time being

**Comment by dkuku** [comment]
This looks like it's done
![jobs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc3a78becd7860013b4e67c/125516c66e82c728ace21e0d46e29b9830c0cfeb9ffbb049a15ee4d6730472257851fa732281b578ec177d005c0b4eac49510947fefd9b37b4f46d2ede0356b49b381d66cc2f10a5b2831abb00b328884881b2b58249d2a5.png)

**Comment by joaopapereira** [comment]
cool :D

**Comment by joaopapereira** [comment]
Going to close this issue as it looks solved by @dkuku screenshot
