### ISSUE TITLE
Job Seeker Status

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#66]
As a Developer
I want to create the model that supports the Job Seeker Status

**Comment by joaopapereira** [comment]
Need t add inserts for the STATUS:
Actively looking for work
Not looking for work
Looking for work

**Comment by amba178** [comment]
Joao, Patric, Vijaya. is possible for STATUS_VALUES to take these key words:
-Active 
-Inactive
-Employed

**Comment by joaopapereira** [comment]
Looks good

**Comment by patmbolger** [comment]
It seems that we want to track two types of status: 1) looking not looking for job, and 2) employed/not employed.

So, maybe we should have all 4 combinations:
Active/Employed
Active/Unemployed
Inactive/Employed
Inactive/Unemployed

After all, a JS could be 'Employed' but either actively *looking* (active) or *not looking* (inactive) for a job, so its probably useful to distinguish between the two.

I could imagine adding the capability for a JD or CM to turn off inactivity alerts for a JS who has status "Inactive/Employed" and perhaps "Active/Employed" as well, so as to concentrate on job seekers who are unemployed (the other two status values).

**Comment by amba178** [comment]
Good point Patric, perhaps you guys have clear understanding of the MetPlus, but I was assuming that initial, when someone comes in into the system looking for a job, mostly likely does not have a job and  starts interacting with CM or JD thus he or she labeled "Active". On other hand, for some reason the interaction and involvement dies thus CM or JD label him as "Inacitve".  If he/she gets  a job thus status becomes "Employed".  Probably, I am wrong. I guess we need to track his employment status too into system.

**Comment by amba178** [comment]
These the STATUS_VALUES and will  have column, value.
agree?
-Unemployed Actively looking for Job
-Employed Actively looking for Job
-Employed Not looking for Job

**Comment by patmbolger** [comment]
Salem - yes, those are the status types that the client agreed to yesterday.  Of course, since we are retaining the status table we can easily add/edit values.

**Comment by amba178** [comment]
Joao -when you say,  "The status should be inserted automatically after this the creation of the table". I can do that, but in future if we decided to edit we just have to mess around with CONSTANT that i created in the model otherwise we have to deal with data tables.
My guess is   we going to use SELECT sort of thing, if we insert the status into the table column..
 we could to use in the views  radios, checkboxs for status and than run validation against the VALUES i have defined inside the model. 

What do you think, I might be wrong.
