### ISSUE TITLE
Chet no longer receives emails for when new users register

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#682]
"I receive emails when their are new users registering on the software. This feature used to work but it stopped."

Aparently Chet stopped receiving emails for new users, can we investigate if there is a regression in this?

**Comment by patmbolger** [comment]
This is probably because the DelayedJob worker is not running in the Azure environment.

On Heroku we had a separate worker for this running `bundle exec rake jobs:work`.

**Comment by joaopapereira** [comment]
This was before the change to azurr. But we need to add that job for azure as well

**Comment by patmbolger** [comment]
I tested locally and all emails work for me.  He should get the queued emails once the worker is started on Azure.

**Comment by joaopapereira** [comment]
The problem was the user we created for Chet was using a different email.
Instead of changing the email addres he configured the new email address and is using it
