### ISSUE TITLE
Activate route for LetsEncrypt

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#683]
we would need to add config in the rails app to force SSL and if we go with free LetsEncrypt certs we'd need to add an endpoint for the app to confirm that we have control of the app

**Comment by tansaku** [comment]
we would need to add config in the rails app to force SSL and if we go with free LetsEncrypt certs we'd need to add an endpoint for the app to confirm that we have control of the app - I've done it for #websiteone and #localsupport

**Comment by tansaku** [comment]
e.g. https://github.com/AgileVentures/WebsiteOne/blob/e095637dce6cf740c8436715e7ea649e568aff25/app/controllers/static_pages_controller.rb#L8

**Comment by joaopapereira** [comment]
@tansaku are we using Certbot to get the certificates?

**Comment by tansaku** [comment]
@joaopapereira yes
