### ISSUE TITLE
Edit the displayed name of the agency in the menu

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#714]
As a PETS administrator
I want to support multiple agencies
So that the application can be more widely used

---

**GIVEN** I am a Agency Administrator
**WHEN** I look at the menu
**THEN** I should see the name of the Agency in the left side

**GIVEN** I am a Agency Administrator
**WHEN** I laccess the administration of my Agency
**AND** Update the Menu Agency Name property
**THEN** I access the main page of the application
**AND** the Menu should reflect my change

*Note:* Currently the title is hardcoded to Met|Plus, we should try to get this information from the `current_agency` helper. 
The visualization part of this story should have been developed on #713

**Comment by ghost** [comment]
hello, i am new to this project and i was on waffle trying to find a task that i could do. I come across this task. I would like to participate in, is this a good task for someone who is new to programming. I can code with html& css, javascript, java, php. thank you

**Comment by joaopapereira** [comment]
Hello @hyper9, Sorry for the late reply. Do you have any question about this task? We can talk in here or in:
https://agileventures.slack.com/messages/C0VEPAPJP
