### ISSUE TITLE
Dynamic description of the agency

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#716]
As a PETS administrator
I want to support multiple agencies
So that the application can be more widely used

---

**GIVEN** I access PETS
**WHEN** I click in the name of the MetPlus
**THEN** I should see the description of the Agency

*Note:* At this point in time the information is hardcoded in the template. We should get the description from the agency object and display that. We can use `current_agency` to get the Agency object

**Comment by NickSchimek** [comment]
What is meant by 'WHEN I click in the name of the MetPlus' ? 
I'm a bit confused where the dynamic description will be located.
Can you point me in the right direction?

**Comment by joaopapereira** [comment]
![Screen Shot 2018-10-15 at 9.23.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e70de2ea6ebc1300f02358/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a371f110284f5e5c5edd3c4a4356bcbbd671f3e57862804e0eebd068567cc46917acbb8749ee02ee208b478ce0bf8848d2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e74d5cac113160e7772431.png)

**Comment by joaopapereira** [comment]
Basically I am talking about the MET|PLUS in the top left corner. The description is what you can see in the bottom of the screenshot

**Comment by tansaku** [comment]
ah, so 

> WHEN I click in the name of the MetPlus

means the same as

> WHEN I am on the MetPlus home page

**Comment by tansaku** [comment]
Some more copy from Chet:

> PETS DESCRIPTION
>
> Public Employment Tracking System – (P.E.T.S) is a web cross-platform software that provides an intuitive closed system employment-related search and connect process where job seekers and employers can locate each other based on required attributes while providing various complementing features. PETS facilitate's a controlled containment of an employment opportunities while managing the systems registered users with real time tracking and interactions between all users by creating comprehensive reports that provide answers and solutions in the employment placement environment.
>
>  Our vision is being able to interconnect job seekers, employers, job developers and case managers while utilizing the PETS system which will in return effectively increase the communication flow between all workforce parties through the PETS System while decreasing the chances of pertinent information or potential job seekers from falling between the cracks of the employment placement process.
