### ISSUE TITLE
Job<>Skills<>Levels - join table creation

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#85]
As a developer
I want to develop a table to associated Jobs with the required skills for that job

**Comment by patmbolger** [comment]
This is the table 'job_skills'.  It is a join table but does contain additional fields beyond foreign keys for each joined table - so, there will be some testing required for those fields.

**Comment by joaopapereira** [comment]
Is this merged?do we have a PR? If not we should move this back

**Comment by patmbolger** [comment]
This was merged 2 days ago - PR #83.

Not sure why it was reopened .... will check with Salem when we talk today.
