### ISSUE TITLE
AgencyPeople - add association

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#88]
This model is missing this association:

has_and_belongs_to_many :job_seekers

**Comment by amba178** [comment]
patrick: 
 i don't  think we can do this     has_and_belongs_to_many :job_seekers, through: :seekers_agency_people

whenever there is :through, we have to use has_many. 
can you check the doc for association, i might be wrong.

**Comment by patmbolger** [comment]
Salem - you are right about using only 'has_many' with a 'through' association.  My comment was incorrect for that as well as the fact that 'seekers_agency_people' is a join table (not a model), so the actual association should be:

has_and_belongs_to_many :job_seekers, join_table: :seekers_agency_people
