### ISSUE TITLE
Administration roles

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#9]
_From @joaopapereira on September 4, 2015 16:30_

I want to be able to create multiple administration role:
Administer resume machine
Add Employer
Aprove Employer
Add Job Developer

_Copied from original issue: AgileVentures/MetPlus_PETS#44_

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
This functionality has been delivered, with the exception of "administer résumé machine" - that is addressed for #8.
