### ISSUE TITLE
Cancancan integration

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#90]
As a developer
I want to integrate cancancan until the application

**Comment by joaopapereira** [comment]
http://hibbard.eu/authentication-with-devise-and-cancancan-in-rails-4-2/

**Comment by joaopapereira** [comment]
In the user model we need to create functions that will allow us to understand what person is this user
is_job_Seeker?
is_job_Developer?
is_casa_Manager?
is_employer?
is_agency_admin?
Is_company_admin?
is_admin?

**Comment by vijayakarumudi** [comment]
I assigned this task to myself.

**Comment by patmbolger** [comment]
1) What is the difference between 'is_admin?' and ''is_agency_admin'?

2) Do we need/want 2 employer roles?  I think we had discussed the idea that anyone employee at an employer could register as an employer contact, and thus create jobs, etc.  - as long as that person know the company credentials (perhaps a PETS-generated company ID?).

3) The process for registering a company (employee) contact will include verification that the given email address domain is that same as the company's email domain (before sending the standard registration email).

**Comment by patmbolger** [comment]
I propose we break this up into two tasks:

1) Cancancan integration - design
2) Cancancan integration - implement

Task 2 would be started *after* a team review of the design.

Task 1 would include roles, roles management, DB design changes (if any), and description of how roles management would be included in controllers (application and role-specific controllers).   This task might include a spike to confirm integration concepts.

**Comment by joaopapereira** [comment]
1) is_admin? is the global administrator level
    is_agency_admin? is the administrator for a specific agency

2) We can have a single role for now

3) I am not sure what is the relation between this question and the cancancan integration, can you elaborate
====================================
About the cancancan integration
There is no definition of what each role is supposed to do or not in this specific ticket. Will we need to have a ticket to say who is allowed to do what? Maybe or maybe not, because some of the other tasks already imply that cancancan need to be configured for that specific part.

So what is expected with this ticket is:
Add the gem to the Gemfile
Create the class needed by cancancan( no need to implement functions there for now)\
Add relational functions to the User model:
 - Check if the user is a job seeker
is_job_seeker? 
 - Check if the user is a job developer
is_job_developer?
 - Check if the user is a case manager 
is_case_manager?
 - Check if the user is a agency admin
is_agency_admin?
 - Check if the user is an employer
is_employer?
 - Check if the user is a global admin
is_admin?

**Comment by patmbolger** [comment]
Item #3 is not a question but just a note that the registration of an employer contact contains an additional step (to confirm that contact's email is a company email address).  No action required on this task.  I will also add to the issue associated with creating an employer contact ...

Re the cancancan design - this would not include defining each specific role authorizations.  However, we do need both a design as well as a team discussion as to how it all comes together so that we can all learn how to incorporate cancancan into role-specific controllers.  This could follow the minimal task that you have outlined above.

**Comment by amba178** [comment]
@patrick:
Yes, it is good idea to discuss as a team on the implementation. Let Vijaya do her chore and whenever she is ready we can review with her. From  my opinion, cancancan can be trick eventhough is not that hard to implement it.

**Comment by vijayakarumudi** [comment]
I Added the gem to the Gemfile
I created the class needed by cancancan( no need to implement functions there for now)\
And I added the  functions to the User model:
