### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#91]
As a User
I want to be able to login to the website

**Comment by joaopapereira** [comment]
The URL should be
/login

We should use the devise page to login. Please check the documentation of Devise to use the templates and change it to something similar in terms of design for what we had before

**Comment by joaopapereira** [comment]
https://github.com/plataformatec/devise#configuring-views

**Comment by joaopapereira** [comment]
Was this login page with the PR of registration?

**Comment by sidhene** [comment]
Yes, originally we wrote separate stories for the registration, login, and logout views. However, devise generates these all automatically, so there was no need for a separate login story. Saleem kept his separate logout story because he had some customization.
