### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#92]
As a Job Seeker
When I access the website 
I want to be able to register to search for jobs

**Comment by joaopapereira** [comment]
The URL should be
/user/new

We should use the devise page to register. Please check the documentation of Devise to use the templates and change it to something similar in terms of design for what we had before

**Comment by joaopapereira** [comment]
https://github.com/plataformatec/devise#configuring-views

**Comment by amba178** [comment]
In case, if you want to generate haml template AFTER creating devise views, default is ERB. No need to install any gem.  
At the root of the app.

rake haml:erb2haml

**Comment by joaopapereira** [comment]
Web registration will be able to choose a branch location
