### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#93]
As a User
I want to be able to logout from the website

**Comment by joaopapereira** [comment]
The URL should be
/user/new

We should use the devise page to register. Please check the documentation of Devise to use the templates and change it to something similar in terms of design for what we had before

**Comment by amba178** [comment]
@joao:
can you check feature/issue-#93
should be a new PR.
is 93 and feature/issue-#93 shoudl be same?

**Comment by joaopapereira** [comment]
The problem is the name of your PR. Just changed it
